### ISSUE TITLE
UI is not adaptive to screen resolution, some buttons are cropped

### ISSUE THREAD

**Issue by Unknown78** [viarotel-org/escrcpy#104]
The UI is not adaptive to screen resolution, the minimum size of the window is too huge for a screen with 1366x786 resolution.

This is non-fullscreen view, minimum size of the window.
![image](https://github.com/viarotel-org/escrcpy/assets/25132599/4e54de73-b33f-4811-9dc2-f167ef30d06a)

This is the fullscreen view.
![image](https://github.com/viarotel-org/escrcpy/assets/25132599/1acb59e5-8a51-43b6-bd4e-bdfc9aeb2a2d)

Notice that on the non-fullsreen view, the button next to the `File Manager` is cropped, there should be `Gnirehtet` and `Mirror Group` right next to it. Also the bottom part of the window is cropped.

While on the fullscreen view, the `Mirror Group` button was cropped. That means my screen resolution is not wide enough to cover the entire UI.

My idea for the solution maybe to have adaptive UI while also reduce minimum window resize limit.

**Comment by viarotel** [comment]
@Unknown78 Please try placing the mouse over the extended menu bar and then scrolling the mouse wheel.

**Comment by Unknown78** [comment]
Okay that method works, but there was no indicator that you could scroll it though.

**Comment by viarotel** [comment]
I will try to continue optimizing it.
