### ISSUE TITLE
mac-arm64 无法运行，提示文件损坏

### ISSUE THREAD

**Issue by kukat** [viarotel-org/escrcpy#107]
运行提示 `“Escrcpy.app” is damaged and can’t be opened. You should move it to the Bin.`

mac console: 
```
default	16:51:20.635940+0800	kernel	ASP: Security policy would not allow process: 96435, /Applications/Escrcpy.app/Contents/MacOS/Escrcpy
```

**Comment by kukat** [comment]
m1 macbook air, 测试了以下版本均无法运行

- Escrcpy-1.14.3-mac-arm64.dmg
- Escrcpy-1.14.3-mac-arm64.zip
- Escrcpy-1.14.2-mac-arm64.dmg
- Escrcpy-1.13.5-mac-arm64.dmg

mac-universal.dmg 可以正常打开

**Comment by viarotel** [comment]
请尝试这个命令 `sudo xattr -r -d com.apple.quarantine [appPath]`

**Comment by viarotel** [comment]
然后在系统设置安全中打开允许任何来源

**Comment by kukat** [comment]
> 请尝试这个命令 `sudo xattr -r -d com.apple.quarantine [appPath]`

可以了

**Comment by viarotel** [comment]
arm版本限制比较严格吧，稍后我会将这个解决方法加入到常见问题中
