### ISSUE TITLE
希望能优化一下延迟问题?

### ISSUE THREAD

**Issue by zoushucai** [viarotel-org/escrcpy#110]
我能明显感觉到, 延长问题(说中文还是英文?)

**Comment by viarotel** [comment]
什么延迟？

**Comment by zoushucai** [comment]
> 什么延迟？

这么快?  投屏延迟问题, 比如我播放视频, 明显和手机显示的画面不同步,要慢一些

**Comment by viarotel** [comment]
你有线还是无线

**Comment by zoushucai** [comment]
有线, 我是 小米手机  + mac m1 电脑,  解决了我投屏的问题, 要是能把延迟问题解决, 就完美了

**Comment by zoushucai** [comment]
感谢

**Comment by viarotel** [comment]
这个基于 scrcpy 我没法优化

**Comment by viarotel** [comment]
正常不应该有延迟，你改配置了？

**Comment by zoushucai** [comment]
我希望视频质量好一些, 我就稍微根据默认值改了一些
<img width="1005" alt="image" src="https://github.com/viarotel-org/escrcpy/assets/15843338/43af9430-fc46-4e67-98fb-fa70c7382c1f">

**Comment by zoushucai** [comment]
参数我不太懂, 我就按照我的理解改的

**Comment by viarotel** [comment]
你还原默认还有延迟吗

**Comment by zoushucai** [comment]
我刚才测试了一下, 默认值, 好像延迟感低很多,  谢谢

**Comment by viarotel** [comment]
嗯嗯 解决了就好

**Comment by zoushucai** [comment]
看来不该动默认参数
