### ISSUE TITLE
无线模式显示“没有获取到局域网连接地址，请检查网络”

### ISSUE THREAD

**Issue by dxgz12138** [viarotel-org/escrcpy#117]
手机连接电脑，点击无线模式显示“没有获取到局域网连接地址，请检查网络”，无法进行无线投屏

**Comment by viarotel** [comment]
没连wifi吗

**Comment by viarotel** [comment]
@dxgz12138 机型和安卓版本分别是？

**Comment by dxgz12138** [comment]
> @dxgz12138 机型和安卓版本分别是？
redmi K50 A13

**Comment by XTTGO** [comment]
@dxgz12138  大概率是因为MIUI单独设置了WIFI调试模式，去开发者里面找选项，填入对应的IP和端口。因为小米不是默认的端口

**Comment by dxgz12138** [comment]
> @dxgz12138 大概率是因为MIUI单独设置了WIFI调试模式，去开发者里面找选项，填入对应的IP和端口。因为小米不是默认的端口
好的，我试试！
