### ISSUE TITLE
无法无线WiFi连接

### ISSUE THREAD

**Issue by Chengxcy** [viarotel-org/escrcpy#12]
同一局域网下，首次通过USB连接后，输入手机无线IP地址后，显示目标计算机积极拒绝访问，连接失败的错误提示框。通过其他投屏软件辅助连接无线投屏一次后此设备才能正常无线投屏，如果再连接其他新设备后又不行，必须再辅助一次，后面才能正常使用。
![image](https://github.com/viarotel-org/escrcpy/assets/91258009/7468456d-8aa8-46a0-b2cf-5cebf71703ab)
USB连接后能否就直接显示该设备的无线（不显示）和有线设备（显示），看其他同类投屏软件都可以的。
![image](https://github.com/viarotel-org/escrcpy/assets/91258009/78c53f43-b8f5-4dbd-8828-d9caf1dcc8be)

**Comment by viarotel** [comment]
你好 抱歉这么晚回复 v1.4.1以上版本 已修复该问题

如果显示无线设备积极拒绝 通常是因为IP地址或端口号错误或者设备与电脑之间未成功建立连接

对于后者情况 我添加了无线配对功能 首次连接失败后 可以通过弹窗页面的无线配对来连接无线设备

至于USB连接后自动发现无线设备 我在行内添加了无线模式入口 欢迎试用
