### ISSUE TITLE
无功放设备上远程控制时远程控制会闪退

### ISSUE THREAD

**Issue by zczhendev** [viarotel-org/escrcpy#121]
```
ERROR: Could not open audio device: WASAPI can't find requested audio endpoin,t: 找不到元素。 ,ERROR: Demuxer error
```

**Comment by viarotel** [comment]
请更新 v1.17.4 后，参阅 [音频捕获异常导致镜像失败](https://github.com/viarotel-org/escrcpy/blob/main/README-CN.md#%E9%9F%B3%E9%A2%91%E6%8D%95%E8%8E%B7%E5%BC%82%E5%B8%B8%E5%AF%BC%E8%87%B4%E9%95%9C%E5%83%8F%E5%A4%B1%E8%B4%A5) 尝试解决该问题
