### ISSUE TITLE
连接时停止充电对应的--no-power-on应该不是这个意思

### ISSUE THREAD

**Issue by shadowwider** [viarotel-org/escrcpy#122]
开始觉得这个功能很好，毕竟插在usb口一直充电有点伤电池。开了之后没效果，去scrcpy看了下觉得--no-power-on 这个命令只是控制启动投屏的时候是否亮屏而不是停止充电。还有--show-touches显示触摸这个功能我开始以为是鼠标点击会有提示，试了下应该只有触摸手机的屏幕才有提示，和开发者工具里的开关一样。建议可以把这些功能在提示里写清楚一点防止像我这样的误会。

停止充电我觉得是个常规功能但是确实没找到简单实现的方式。最后参考了[acc](https://github.com/VR-25/acc)项目是可以了，但是必须要root还要adb命令。因为简单停止充电会导致--stay-awake这个命令又不起效果，大概是系统觉得没有电要省着点用吧... 最后用了`adb shell dumpsys battery set usb 1`这个命令才欺骗系统让它保持亮屏。

**Comment by viarotel** [comment]
v1.16.7 已解决该问题
