### ISSUE TITLE
希望能对鼠标的功能键提供支持

### ISSUE THREAD

**Issue by 1ilin** [viarotel-org/escrcpy#123]
鼠标的后退键目前控制的是手机的切换键，前进键控制的是打开通知中心，希望可以自定义鼠标功能键的操作

**Comment by bigfoxtail** [comment]
低端鼠标没法自定义案件功能的那种，鼠标的前后键相当于alt+左右键，你可以看看哪里能改这个快捷键的功能

**Comment by GreatOnDeck** [comment]
更新至 v2.4 版本的 scrcpy，使用参数 "--forward-all-clicks -K -M"
