### ISSUE TITLE
adb路径不支持中文路径，使用中文路径会报错

### ISSUE THREAD

**Issue by JeffCheung85** [viarotel-org/escrcpy#124]
![PixPin_2023-12-08_11-40-13](https://github.com/viarotel-org/escrcpy/assets/49676276/bbee5385-5f72-4dc8-bd60-970e58fee7c4)

**Comment by wuyusite** [comment]
同样遇到此问题，换成全英文路径后正常

**Comment by viarotel** [comment]
该问题已过时
