### ISSUE TITLE
当手机意外断开时，无法取消黑屏状态

### ISSUE THREAD

**Issue by ooil929** [viarotel-org/escrcpy#125]
开启“控制时关闭屏幕”功能连接后，当数据线接触不良或直接拔掉数据线断开连接时 手机会一直处于黑屏状态 按电源键和屏幕都无法恢复亮屏，只能再重新连接Esrcpy再正常关闭连接后才能恢复

**Comment by JeffCheung85** [comment]
锁屏键按几次就出来了

**Comment by ooil929** [comment]
> 锁屏键按几次就出来了

出不来的，快速按十几次都没用，可能是安卓14的原因。
