### ISSUE TITLE
[Feature Request] Audio Only Mode

### ISSUE THREAD

**Issue by HDark15** [viarotel-org/escrcpy#132]
Putting this command  ```--no-video``` on the arguments box will give an error (sometimes) ```Operation Failed``` at the first run and will works without error on the second run. Clicking Refresh will make the mirror button available to click, and clicking it again will make the audio double. To stop the run or fix the audio, either close the program or disconnect the phone, if the phone disconnected it will give the same error ```Operation Failed``` as many times as you click the mirror button.

**Comment by viarotel** [comment]
In V1.19.4, the scrcpy has been updated to V2.5. It seems that the problem has been solved, please try it out
