### ISSUE TITLE
[BUG]无限的刷新设备有gif

### ISSUE THREAD

**Issue by XTTGO** [viarotel-org/escrcpy#133]
![bug](https://github.com/viarotel-org/escrcpy/assets/38094114/7d81ac20-1a74-4881-b086-86c3969cef11)
我打开软件什么都不操作，就成了这样了

**Comment by XTTGO** [comment]
重启了下电脑又好了，估计是什么冲突了

**Comment by huixu007** [comment]
你好请问是如何解决的？我这也碰到了这个问题
