### ISSUE TITLE
启动时支持一次性配置

### ISSUE THREAD

**Issue by xiaobaimc** [viarotel-org/escrcpy#135]
这个软件很好用，很适合我这种不想写bat的人
我在使用了这个软件之后提了一些建议：
-增加单独的音频，视频开关。不然每次都要去scrcpy参数里面设置，例如--no-audio
-增加一个二级窗口
![屏幕截图 2023-12-29 065231](https://github.com/viarotel-org/escrcpy/assets/113223243/256bfd39-9944-4bb9-aa2f-38c811da5ed9)
在点击“开始镜像”时，弹出一个二级窗口，上面显示视频 音频对应的参数，确定和否的按钮，以及增加几个开关
比如1.使用OTG模式 2.关闭音频捕获 3.使用摄像 等等
-将“偏好设置”里面其中一些常用选项合并到主界面
-debug模式优化，点击运行日志单独弹出一个窗口，而不是直接打开txt文件
最后
我想说的是，市面上很少有这种良心软件了
bug多，软件开发不容易，尤其是这种开源软件，能理解
一个小问题：前端和后端开发不是同一个人吧？软件里面经常遇到前后端打架的情况

**Comment by viarotel** [comment]
首先非常感谢您的支持和建议，需求这一块我很受启发，实现和交互这一块我认为还可以更好，因为最近在为生活忙碌，所以我会在有空闲时间的时候尝试优化它。

**Comment by viarotel** [comment]
[v1.21.4](https://github.com/viarotel-org/escrcpy/releases/tag/v1.21.4) 已支持 `更多操作`->`灵活启动`
