### ISSUE TITLE
三星S23，偏好设置里任何改动都会触发错误

### ISSUE THREAD

**Issue by zhl111** [viarotel-org/escrcpy#137]
我下载的是免安装便携版，与此有关吗？
但，即使重置后仍然提示同样的错误
![image](https://github.com/viarotel-org/escrcpy/assets/29135984/47b6c893-eb66-4026-ae6a-775f9b560e0a)

**Comment by viarotel** [comment]
请尝试开启调试模式提供更多信息，或者使用内置终端手动执行相应的命令查看有无额外的输出

**Comment by zhl222** [comment]
我重置手机了，再连接你这个软件，又变灰了！！！！
难道我还得重置手机吗？这什么情况

**Comment by viarotel** [comment]
解决了么? 抱歉我没有三星手机无法复现你描述的问题
