### ISSUE TITLE
请教，输入问题

### ISSUE THREAD

**Issue by zhl222** [viarotel-org/escrcpy#138]
我的笔记本的键盘输入不能和手机互动，同样是搜狗输入法也不行。我该如何设置？

**Comment by viarotel** [comment]
电脑的的输入法需要切换到英文状态下

**Comment by zhl222** [comment]
是，我发现了，但只能输入英文吗？中文可以吗？

**Comment by zhl222** [comment]
![image](https://github.com/viarotel-org/escrcpy/assets/155349357/d570579c-c2b4-4f7f-b1b6-2add9b71d4a8)
不过，它是在手机上安装了app，用自带的输入法替换了

**Comment by xiamo008** [comment]
你好，我电脑和手机都安装了，搜狗输入法，但是电脑切换到中文上后，手机就无法输入，电脑切换到英文后，手机可输入，但是只能输入字母数字，无法正常拼音 输入中文，求指导 我是iq10 手机
