### ISSUE TITLE
摄像头功能无法单独使用

### ISSUE THREAD

**Issue by YumeMichi** [viarotel-org/escrcpy#140]
我现在连接了两部设备，其中一部只是为了使用摄像头功能。
如果在设置里打开启用摄像，那么所有连接的设备都会变成打开摄像头。

**Comment by viarotel** [comment]
是否通过偏好设置上方的作用域范围分别进行配置？

**Comment by YumeMichi** [comment]
> 是否通过偏好设置上方的作用域范围分别进行配置？

啊这，居然没注意到上面有个下拉框
