### ISSUE TITLE
终端调试功能异常

### ISSUE THREAD

**Issue by little-alei** [viarotel-org/escrcpy#145]
终端调试中，如果运行错误的指令，会导致没有任何响应，且不能删除此cmd命令，需要重启escrcpy才可以再输入命令

**Comment by viarotel** [comment]
> 终端调试中，如果运行错误的指令，会导致没有任何响应，且不能删除此cmd命令，需要重启escrcpy才可以再输入命令

你好 请问你是什么平台 运行的命令是什么 我测试了一下如果运行不受支持的命令会提示 command not found 并没有复现你所说的问题

**Comment by little-alei** [comment]
> > 终端调试中，如果运行错误的指令，会导致没有任何响应，且不能删除此cmd命令，需要重启escrcpy才可以再输入命令
> 
> 你好 请问你是什么平台 运行的命令是什么 我测试了一下如果运行不受支持的命令会提示 command not found 并没有复现你所说的问题

win64平台，比如随便输入一个，adb shell aaaa 就不动了

**Comment by viarotel** [comment]
v1.17.2 已经修复该问题

**Comment by little-alei** [comment]
> v1.17.2 已经修复该问题

效率杠杠滴
