### ISSUE TITLE
希望添加录屏和截屏

### ISSUE THREAD

**Issue by RDsatan** [viarotel-org/escrcpy#15]
快捷录屏和截屏可是测试环境必备的功能啊

**Comment by viarotel** [comment]
v1.5.1已添加录屏功能，截图功能也快了

**Comment by RDsatan** [comment]
能否添加快捷键截屏功能？如alt+z主屏截屏

**Comment by viarotel** [comment]
> 能否添加快捷键截屏功能？如alt+z主屏截屏

v1.6.0 已加入截图功能 暂时就这样吧 肝不动了 快捷键功能 scrcpy 内置了一些 为了未来避免冲突 暂时没有计划加入
