### ISSUE TITLE
多屏协同功能会造成systemui崩溃？

### ISSUE THREAD

**Issue by LoadingP** [viarotel-org/escrcpy#151]
这边测试了3台设备，2部手机+1部平板，都会发生如此问题，我这边确认过三台设备都会在开启多屏的一瞬间就会发生UI崩溃重启
(https://github.com/viarotel-org/escrcpy/assets/50085558/e1e989e1-167c-499a-9c41-ef73b4d992a2)

**Comment by viarotel** [comment]
> 这边测试了3台设备，2部手机+1部平板，都会发生如此问题，我这边确认过三台设备都会在开启多屏的一瞬间就会发生UI崩溃重启
> 
> (https://github.com/viarotel-org/escrcpy/assets/50085558/e1e989e1-167c-499a-9c41-ef73b4d992a2)
> 
> 

这个功能需要系统支持，普遍情况下国产的手机系统会崩溃，经测试LinageOS20可以完美支持，魅族的系统似乎也可以

**Comment by LoadingP** [comment]
> > 这边测试了3台设备，2部手机+1部平板，都会发生如此问题，我这边确认过三台设备都会在开启多屏的一瞬间就会发生UI崩溃重启
> > (https://github.com/viarotel-org/escrcpy/assets/50085558/e1e989e1-167c-499a-9c41-ef73b4d992a2)
> 
> 这个功能需要系统支持，普遍情况下国产的手机系统会崩溃，经测试LinageOS20可以完美支持，魅族的系统似乎也可以

这台手机是电信运营商定制的天翼1号2022，也是魅族flyme系统，但是有不少魔改。不知道是不是这个导致的

**Comment by iswbm** [comment]
我这边 8 台小米手机，也全都会崩溃，无法使用

**Comment by viarotel** [comment]
> 我这边 8 台小米手机，也全都会崩溃，无法使用

小米的ROM定制化太多不行的
