### ISSUE TITLE
Auto-connect extra choice: auto-mirror

### ISSUE THREAD

**Issue by marcosilva85** [viarotel-org/escrcpy#153]
Hi, I use escrcpy with USB cable (since wifi 2.4 and 5Ghz  video stream always lags and stops after some seconds),
but USB cable works wonderful, realtime and with perfect audio.

Would it be possible to have a setting to auto-mirror when I connect the phone with USB cable to my Linux computer?  

It would be wonderful to have an option to **automatically display the screen just after the phone is connected**, since I often switch around 2 phones via USB-cable to make them display on my TV, however I am always having to interact with the computer to manually run the mirroring.

I could not find this setting in escrcpy, besides the auto-connect.

**Comment by viarotel** [comment]
v1.17.6 Supported auto-mirror
