### ISSUE TITLE
粘贴板问题，导致复制后无法在本地电脑粘贴，但是手机可以

### ISSUE THREAD

**Issue by LinuxBoxing** [viarotel-org/escrcpy#155]
粘贴板问题，导致在本地电脑复制后无法在本地电脑粘贴，但是手机可以粘贴，之前的scrcpy不存在这种情况。问题发生在Android11而Android14没有

**Comment by xiamo008** [comment]
你在设置里面，选择鼠标模式SDK 键盘模式选择UHID 就可以了

**Comment by LinuxBoxing** [comment]
> 你在设置里面，选择鼠标模式SDK 键盘模式选择UHID 就可以了

并不能解决

**Comment by xiamo008** [comment]
> > 你在设置里面，选择鼠标模式SDK 键盘模式选择UHID 就可以了
> 
> 并不能解决

那就不清楚了，我是iq10。最新的14系统，电脑是win10，我是可以正常复制粘贴的，双向都行。

**Comment by LinuxBoxing** [comment]
> > > 你在设置里面，选择鼠标模式SDK 键盘模式选择UHID 就可以了
> > 
> > 
> > 并不能解决
> 
> 那就不清楚了，我是iq10。最新的14系统，电脑是win10，我是可以正常复制粘贴的，双向都行。

我另一台安卓14也是没有问题

**Comment by xiamo008** [comment]
> > > > 你在设置里面，选择鼠标模式SDK 键盘模式选择UHID 就可以了
> > > 
> > > 
> > > 并不能解决
> > 
> > 
> > 那就不清楚了，我是iq10。最新的14系统，电脑是win10，我是可以正常复制粘贴的，双向都行。
> 
> 我另一台安卓14也是没有问题

那有没有可能是手机本身的问题，因为你不是有一台手机是正常的嘛。

**Comment by LinuxBoxing** [comment]
> > > > > 你在设置里面，选择鼠标模式SDK 键盘模式选择UHID 就可以了
> > > > 
> > > > 
> > > > 并不能解决
> > > 
> > > 
> > > 那就不清楚了，我是iq10。最新的14系统，电脑是win10，我是可以正常复制粘贴的，双向都行。
> > 
> > 
> > 我另一台安卓14也是没有问题
> 
> 那有没有可能是手机本身的问题，因为你不是有一台手机是正常的嘛。

用之前的版本就没这种情况，所以很奇怪

**Comment by viarotel** [comment]
可以尝试自定义 scrcpy 依赖版本为老版本看看能否解决

**Comment by puwei7788** [comment]
我的荣耀Magic5（安卓14）上的问题是，电脑上复制的可以在手机上粘贴，在手机上复制的不能在电脑上粘贴，升级了好几版Scrcpy了，都还是这样。另一个老问题是按Alt+o不能关闭设备屏幕~

**Comment by puwei7788** [comment]
> 你在设置里面，选择鼠标模式SDK 键盘模式选择UHID 就可以了

是在哪个的设置里哈？手机还是电脑？怎么选择UHID模式呢？

**Comment by YumeMichi** [comment]
> [server] ERROR: Could not invoke method java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.getPrimaryClip [class java.lang.String, class java.lang.String, class java.lang.String, class java.lang.String, int, int, boolean] at java.lang.Class.getMethod(Class.java:2937) at java.lang.Class.getMethod(Class.java:2449) at com.genymobile.scrcpy.wrappers.ClipboardManager.getGetPrimaryClipMethod(ClipboardManager.java:64) at com.genymobile.scrcpy.wrappers.ClipboardManager.getText(ClipboardManager.java:152) at com.genymobile.scrcpy.Device.getClipboardText(Device.java:290) at com.genymobile.scrcpy.Device$3.dispatchPrimaryClipChanged(Device.java:143) at android.content.IOnPrimaryClipChangedListener$Stub.onTransact(IOnPrimaryClipChangedListener.java:84) at android.os.Binder.execTransactInternal(Binder.java:1371) at android.os.Binder.execTransact(Binder.java:1310) [server] ERROR: Could not invoke method java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.getPrimaryClip [class java.lang.String, class java.lang.String, class java.lang.String, class java.lang.String, int, int, boolean] at java.lang.Class.getMethod(Class.java:2937) at java.lang.Class.getMethod(Class.java:2449) at com.genymobile.scrcpy.wrappers.ClipboardManager.getGetPrimaryClipMethod(ClipboardManager.java:64) at com.genymobile.scrcpy.wrappers.ClipboardManager.getText(ClipboardManager.java:152) at com.genymobile.scrcpy.Device.getClipboardText(Device.java:290) at com.genymobile.scrcpy.Device$3.dispatchPrimaryClipChanged(Device.java:143) at android.content.IOnPrimaryClipChangedListener$Stub.onTransact(IOnPrimaryClipChangedListener.java:84) at android.os.Binder.execTransactInternal(Binder.java:1371) at android.os.Binder.execTransact(Binder.java:1310)
> 
> ——scrcpy使用中出现的上述问题，使得手机上复制的内容不能传递给电脑

你这不应该去scrcpy那边开issue吗

**Comment by puwei7788** [comment]
> 你在设置里面，选择鼠标模式SDK 键盘模式选择UHID 就可以了

scrcpy --mouse=sdk --keyboard=uhid 这样没用哈~

**Comment by puwei7788** [comment]
> > [server] ERROR: Could not invoke method java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.getPrimaryClip [class java.lang.String, class java.lang.String, class java.lang.String, class java.lang.String, int, int, boolean] at java.lang.Class.getMethod(Class.java:2937) at java.lang.Class.getMethod(Class.java:2449) at com.genymobile.scrcpy.wrappers.ClipboardManager.getGetPrimaryClipMethod(ClipboardManager.java:64) at com.genymobile.scrcpy.wrappers.ClipboardManager.getText(ClipboardManager.java:152) at com.genymobile.scrcpy.Device.getClipboardText(Device.java:290) at com.genymobile.scrcpy.Device$3.dispatchPrimaryClipChanged(Device.java:143) at android.content.IOnPrimaryClipChangedListener$Stub.onTransact(IOnPrimaryClipChangedListener.java:84) at android.os.Binder.execTransactInternal(Binder.java:1371) at android.os.Binder.execTransact(Binder.java:1310) [server] ERROR: Could not invoke method java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.getPrimaryClip [class java.lang.String, class java.lang.String, class java.lang.String, class java.lang.String, int, int, boolean] at java.lang.Class.getMethod(Class.java:2937) at java.lang.Class.getMethod(Class.java:2449) at com.genymobile.scrcpy.wrappers.ClipboardManager.getGetPrimaryClipMethod(ClipboardManager.java:64) at com.genymobile.scrcpy.wrappers.ClipboardManager.getText(ClipboardManager.java:152) at com.genymobile.scrcpy.Device.getClipboardText(Device.java:290) at com.genymobile.scrcpy.Device$3.dispatchPrimaryClipChanged(Device.java:143) at android.content.IOnPrimaryClipChangedListener$Stub.onTransact(IOnPrimaryClipChangedListener.java:84) at android.os.Binder.execTransactInternal(Binder.java:1371) at android.os.Binder.execTransact(Binder.java:1310)[服务器]错误：无法调用方法java.lang.NoSuchMethodException：android.content.IClipboard$Stub$Proxy.getPrimaryClip [class java.lang. String，class java. lang. String，class java. lang. String，class java. lang.String，int，int，boolean] at java.lang.Class.getMethod（Class.java：2937）在java.lang.Class.getMethod（Class.java：2449），位于com.genymobile. cncpy.wrappers.ClipboardManager.getGetPrimaryClipMethod（ClipboardManager.java：64），网址为：com.genymobile. wrappers.ClipboardManager.getText（ClipboardManager.java：152）位于com.genymobile. configcpy.Device.getClipboardText（Device.java：290），网址为com.genymobile.juncpy.Device$3.dispatchPrimaryClipChanged（Device.java：143）在android.content. IOnPrimaryClipChangedList $Stub.onTransact（IOnPrimaryClipChangedListener.java：84）at android.os.Binder.execTransactInternal（Binder.java：1371）at android.os.Binder.execTransact（Binder.java：1310）[server]错误：无法调用java.lang.NoSuchMethodException：android.content.IClipboard$Stub$Proxy.getPrimaryClip [class java.lang.String，class java.lang.String，class java. lang. String，class java. lang.String，class java.lang.String，int，int，boolean] at java.lang.Class.getMethod（Class.java：2937）在java.lang.Class.getMethod（Class.java：2449），位于com.genymobile. cncpy.wrappers.ClipboardManager.getGetPrimaryClipMethod（ClipboardManager.java：64），网址为：com.genymobile. wrappers.ClipboardManager.getText（ClipboardManager.java：152）位于com.genymobile. configcpy.Device.getClipboardText（Device.java：290），网址为com.genymobile.juncpy.Device$3.dispatchPrimaryClipChanged（Device.java：143）at android.content.IOnPrimaryClipChangedListener$Stub.onTransact（IOnPrimaryClipChangedListener. java：84）at android.os.Binder.execTransactInternal（Binder. java：1371）at android.os.Binder.execTransact（Binder.java：1310）
> > ——scrcpy使用中出现的上述问题，使得手机上复制的内容不能传递给电脑
> 
> 你这不应该去scrcpy那边开issue吗

哈哈哈，不好意思，找错地方了~
