### ISSUE TITLE
输入密码黑屏的问题

### ISSUE THREAD

**Issue by xiamo008** [viarotel-org/escrcpy#157]
你好大佬，请问在映射时候，遇到输入密码等情况时，映射的手机屏幕就会自动黑屏，请问这个可以解决吗，就是强制不黑屏，不管在什么时候。

**Comment by viarotel** [comment]
这个是安卓安全限制导致的，暂时没有更好的解决办法，我目前是将闲置手机改为没有任何密码的滑动解锁后不会有这个问题

**Comment by xiamo008** [comment]
> 这个是安卓安全限制导致的，暂时没有更好的解决办法，我目前是将闲置手机改为没有任何密码的滑动解锁后不会有这个问题

这样子，谢谢，我平时主要是用来转账多，就想着电脑输入密码就会方便点。结果不行，不过还是谢谢大佬的回复了、

**Comment by viarotel** [comment]
ok

**Comment by youli42** [comment]
可以通过模块解决这个问题，但是使用的前提是已经root……就很难受（参考链接：[使用模块解决远程黑屏问题](https://www.bilibili.com/video/BV1cGHEePEg4/?vd_source=f92a2f3367b863030638e1aca838fb57)）其他方法还在找

**Comment by liuzhao2** [comment]
> 你好大佬，请问在映射时候，遇到输入密码等情况时，映射的手机屏幕就会自动黑屏，请问这个可以解决吗，就是强制不黑屏，不管在什么时候。

加启动参数--stay-awake
