### ISSUE TITLE
mac m2 无法使用镜像功能

### ISSUE THREAD

**Issue by ffdsss** [viarotel-org/escrcpy#158]
安卓10 、安卓11、安卓12、安卓13都不行

![image](https://github.com/viarotel-org/escrcpy/assets/48895716/d35107e0-fc72-4d56-a746-82a0a934968c)

**Comment by viarotel** [comment]
您似乎没有安装scrcpy作为依赖项。请参考 https://github.com/viarotel-org/escrcpy#macos--linux

**Comment by ffdsss** [comment]
> 您似乎没有安装 scrcpy 作为依赖项。请参考https://github.com/viarotel-org/escrcpy#macos--linux

可以了  🙏
