### ISSUE TITLE
几个小建议，请开发者查收~

### ISSUE THREAD

**Issue by ihuge820920** [viarotel-org/escrcpy#159]
几个建议：
①希望可以添加一个记住指定IP设备的功能，保留在首页，而不是仅有的历史记录
②域名+端口连接的设备好像不支持断开连接
③可以删除历史记录里的部分设备吗？每次点击IP输入窗格都会跳出来

**Comment by 2284787774** [comment]
还有控制设备的功能栏例如切换键、主屏幕、返回键这些能固定到镜像画面旁边吗

**Comment by esbylan** [comment]
我也提一个建议，可以把加个设置开启/关闭设备的操作栏（返回键，主屏幕和切换键那些）附着在镜像窗口下边，这样比较类似正经模拟器的交互了

**Comment by Heanes** [comment]
> 我也提一个建议，可以把加个设置开启/关闭设备的操作栏（返回键，主屏幕和切换键那些）附着在镜像窗口下边，这样比较类似正经模拟器的交互了

附议，这样更便捷
