### ISSUE TITLE
各位是否遇到丢音的问题？

### ISSUE THREAD

**Issue by YumeMichi** [viarotel-org/escrcpy#16]
就是时不时声音断一下，尤其是在操作其他应用的情况下。比如打开别的软件，浏览器开新的网页等操作。

**Comment by viarotel** [comment]
我测试了一下暂时没有发现这个问题 这个是基于 scrcpy 的原生音频转发 如果有问题请向 scrcpy 
 提 [issues](https://github.com/Genymobile/scrcpy/issues)

**Comment by YumeMichi** [comment]
好的谢谢
