### ISSUE TITLE
不支持Win7吗，打开错误

### ISSUE THREAD

**Issue by wilsonjor** [viarotel-org/escrcpy#161]
不支持Win7吗，打开错误

**Comment by viarotel** [comment]
是的 https://github.com/viarotel-org/escrcpy/blob/main/README-CN.md#%E6%97%A0%E6%B3%95%E5%AE%9A%E4%BD%8D%E7%A8%8B%E5%BA%8F%E8%BE%93%E5%85%A5%E7%82%B9-discardvirtualmemory-%E4%BA%8E%E5%8A%A8%E6%80%81%E9%93%BE%E6%8E%A5%E5%BA%93-kernel32dll-%E4%B8%8A
