### ISSUE TITLE
启用OTG失败

### ISSUE THREAD

**Issue by yuu023** [viarotel-org/escrcpy#162]
机型：nova9
错误提示：ERROR: OTG mode: could not turn screen off

**Comment by viarotel** [comment]
和 `控制时关闭屏幕` 冲突了 你先手动关一下 我下个版本处理一下

**Comment by viarotel** [comment]
[v1.17.8](https://github.com/viarotel-org/escrcpy/releases/tag/v1.17.8) 已解决该问题
