### ISSUE TITLE
360报毒

### ISSUE THREAD

**Issue by SSR-Bit** [viarotel-org/escrcpy#165]
类型：
Win64/Trojan.Generic.HgEATGsA

描述：
Win64/Trojan.Generic.HgEATGsA

扫描引擎：
360云查杀引擎

文件路径：
C:\Users\XXX\Downloads\Escrcpy-1.17.7-win-x64.zip

文件指纹(MD5)：
122d613c876a158c929e65162bf47d11

**Comment by viarotel** [comment]
因为没有签名，或者说没有给360缴费吧，软件是开源的你可以看到源代码，360这玩意只会加重电脑负担，火绒也比这玩意好
