### ISSUE TITLE
please merge scrcpy and adb in appimage . my os cannot install it , thank you :)

### ISSUE THREAD

**Issue by newyorkthink** [viarotel-org/escrcpy#173]
![image](https://github.com/viarotel-org/escrcpy/assets/87791643/f5a6e717-809c-41d0-b1a0-703dfa789500)

**Comment by viarotel** [comment]
Sorry to reply you so late, scrcpy does not provide a separate binary file in Linux, so I do not have a more convenient way to integrate it for the time being. If you have a better scheme, please pull the request

**Comment by viarotel** [comment]
x86 version of linux has integrated scrcpy
