### ISSUE TITLE
[Bug] 无线配对时命令执行错误

### ISSUE THREAD

**Issue by qingkong9579** [viarotel-org/escrcpy#176]
为所有用户安装时，adb路径位于C:\Program Files\Escrcpy\resources\extra\win\android-platform-tools\adb.exe
推测为路径中Program Files中的空格导致的问题，更换路径后恢复正常

**Comment by viarotel** [comment]
[v1.18.4](https://github.com/viarotel-org/escrcpy/releases/tag/v1.18.4) 已修复该问题
