### ISSUE TITLE
Linux上的图标问题

### ISSUE THREAD

**Issue by zxp19821005** [viarotel-org/escrcpy#181]
如题。
我已经将其移植到了ArchLinux的AUR：
- https://aur.archlinux.org/packages/escrcpy-bin
- https://aur.archlinux.org/packages/escrcpy
在`electron-builder.json`中Linux打包的图标定义为`logo.icns`(这个应该是MacOS上的图标格式)，实际上应该为`logo.png`。

**Comment by viarotel** [comment]
我查看了文档 https://www.electron.build/icons.html，linux的图标可以是 `.icns`， `electron-builder` 将会自动处理它，我打完包已经测试过在 ubuntu 上图标运行良好

**Comment by zxp19821005** [comment]
不知道别的Linux发行版是怎样的，根据 https://www.electron.build/icons.html#linux 来看，electron确实是可以通过macOS的icns来生成png文件，这个我倒是没有测试过，我是直接修改了配置文件，指向了'logo.png'。
我在进行编译打包的时候，是不生成任何Linux发行版的安装包的，而是直接生成的目录(减少各种乱七八糟的依赖，减少编译时间)，不知道能否调用这个功能，我再测试一下吧。
