### ISSUE TITLE
很不错的项目

### ISSUE THREAD

**Issue by pigadmin** [viarotel-org/escrcpy#182]
点个赞  页面的UI简洁，性能都很不错，希望可以脱离官方UI，解码绘制到vue页面视图，实现群控 画面同步，指令下发功能。
借鉴了~
![0d8e4b0ea1a9e7535241b2cb9ace978c](https://github.com/viarotel-org/escrcpy/assets/8655006/35d3be63-80d9-4fbe-b46a-5664dd3d14f4)

**Comment by viarotel** [comment]
感谢支持，后面会考虑你的建议
