### ISSUE TITLE
[BUG] Shortcut "CTRL+F" not working in other apps, after minimizing escrcpy to tray

### ISSUE THREAD

**Issue by VINTX2** [viarotel-org/escrcpy#183]
Hello,

when I minimize escrcpy to tray (close window -> Minimize to tray) the keyboard short "CTRL+F" stops working in other applications.

My system:
OS: Arch Linux Kernel 6.9.1
Desktop Environment: GNOME 46
escrcpy version: 1.19.0-1

Thank you for this nice software!

**Comment by viarotel** [comment]
v1.19.1 已修复该问题
