### ISSUE TITLE
控制时关闭屏幕失效

### ISSUE THREAD

**Issue by zengsongfeng** [viarotel-org/escrcpy#185]
手机型号是荣耀70
偏好设置中选择“控制时关闭屏幕”，之后点击“开始镜像”。
镜像开启时闪屏退出，同时提示错误信息。
错误提示信息：Native registration unable to find class 'com/android/server/TrustedUlService' aborting...,Aborted ,WARN: Device disconnected

**Comment by iamlinkent** [comment]
碰到同样问题，魅族flyme，安卓14

**Comment by YumeMichi** [comment]
应该是scrcpy的bug
https://github.com/Genymobile/scrcpy/issues/4823
