### ISSUE TITLE
Windows下无法关闭软件了🥺

### ISSUE THREAD

**Issue by ChiehJang** [viarotel-org/escrcpy#189]
我安装后使用一切正常，点击关闭按钮后有一个『记住选择』的☑️复选框我勾选了，我手滑点了不退出，现在点击关闭再也无法关闭了，只有在任务管理器结束进程了，有什么办法解决吗？

**Comment by viarotel** [comment]
恭喜你发现了一个BUG，暂时的解决方法是 在 `偏好设置` => `编辑` 中手动 将 	`appCloseCode`  配置删掉

**Comment by viarotel** [comment]
该问题已修复 v1.19.3
