### ISSUE TITLE
[功能请求]希望可以增加多显示器支持

### ISSUE THREAD

**Issue by Vixb1122** [viarotel-org/escrcpy#192]
可用的命令：
列出所有显示器
`scrcpy --list-displays`
镜像指定的显示器
`scrcpy --display-id=0`

**Comment by viarotel** [comment]
是支持的 请前往 `偏好设置->视频控制->显示器 `  输入显示器ID（如果你已从全局切换到指定设备上则将会自动检测当前设备可用的显示器）

**Comment by Vixb1122** [comment]
好，看到了，就是不知道能不能支持同时镜像多个显示器。 @viarotel

**Comment by viarotel** [comment]
目前你可以通过使用多屏协同（需要ROM支持）或者在每次修改显示器ID后多次执行镜像进行类似的实现

**Comment by Vixb1122** [comment]
@viarotel 如果有多个显示器时，可以在列表中提供个快捷下拉选择框不
![image](https://github.com/viarotel-org/escrcpy/assets/17810492/1aa90392-2eeb-4eca-9727-7a4f9b4d969d)

**Comment by viarotel** [comment]
后面会考虑加上
