### ISSUE TITLE
截取屏幕 请求增加jpg格式设置

### ISSUE THREAD

**Issue by 379061296** [viarotel-org/escrcpy#196]
需要大量截图，请求增加jpg格式设置，设置间隔时间循环自动截屏，关闭截屏成功提示

![QQ截图20240621002723](https://github.com/viarotel-org/escrcpy/assets/21965603/4d1f9cd7-8e33-41bf-bd5b-7cdc3ba6813d)

**Comment by viarotel** [comment]
[v1.21.4](https://github.com/viarotel-org/escrcpy/releases/tag/v1.21.4) 已优化该功能，设置间隔时间循环自动截屏请尝试`执行脚本`功能
