### ISSUE TITLE
关于录制和动作的功能

### ISSUE THREAD

**Issue by ganzi01234** [viarotel-org/escrcpy#197]
大佬，是否考虑加入录制动作操作，然后回放的功能？

**Comment by viarotel** [comment]
没太明白你需求，你的意思是我需要做一个类似与动作检测的功能，检测到特定的动作自动录制？

**Comment by ganzi01234** [comment]
有个录制按钮，录制系列操作。然后回放自动重新重复该系列操作。用于自动化测试等场景。
