### ISSUE TITLE
使用文档中的搜狗输入法后win系统还是没法输入中文

### ISSUE THREAD

**Issue by Member-99** [viarotel-org/escrcpy#203]
![image](https://github.com/viarotel-org/escrcpy/assets/166231526/40f21af6-43df-4ac7-bb5e-b3608a18eec0)
请问下是哪里的设置还需要更改吗，或者需要其他的输入法，在使用scrpy中是正常的

**Comment by Member-99** [comment]
机型是小米6，我这里切换到英文，手机也输入的英文，改为中文后手机无法获取到输入，手机搜狗输入法正常

**Comment by viarotel** [comment]
电脑上保持英文输入状态，手机上切换到中文输入
