### ISSUE TITLE
Dear~ I have provided feedback on some issues

### ISSUE THREAD

**Issue by DamonlucklyD** [viarotel-org/escrcpy#205]
I use huwei p30,and then following this situations...

[server] WARN: Audio disabled: it is not supported before Android 11 ,[server] ERROR: Video encoder 'OMX.qcom.video.encoder.avc' for h264 not found List of video encoders: --video-codec=h264 --video-encoder='OMX.hisi.video.encoder.avc' --video-codec=h264 --video-encoder='c2.android.avc.encoder' --video-codec=h264 --video-encoder='OMX.google.h264.encoder' --video-codec=h265 --video-encoder='OMX.hisi.video.encoder.hevc' --video-codec=h265 --video-encoder='c2.android.hevc.encoder' ,ERROR: Controller error ERROR: Demuxer 'video': stream disabled due to connection error ERROR: Demuxer 'audio': stream disabled due to connection error

**Comment by viarotel** [comment]
Please try to adjust the video in the preference settings and disable audio output
