### ISSUE TITLE
能不能像安联一样增加一个文件管理系统以及虚拟按键啊? 每次都要好几个窗口一起使用好麻烦

### ISSUE THREAD

**Issue by MushuScript** [viarotel-org/escrcpy#213]
这是安联的软件: https://cn.anlinksoft.com/

不过安联貌似停更了, 不支持安卓14的系统. 但是它的功能细节都做很好啊

文件管理
虚拟导航

**Comment by MushuScript** [comment]
作者貌似不想采取

**Comment by viarotel** [comment]
你好朋友

首先非常感谢你对Escrcpy的支持和建议!你的反馈真的让我很受鼓舞。

我懂你对新功能的渴望,说实话,我也很想把它们都加进去。但正如README里提到的,有些功能(比如那个镜像窗口的交互栏)实现起来真的比看上去复杂多了。至于通过界面管理手机文件,这个想法很棒,我已经把它记在我的"待办"清单上了。

不过呢,实话实说,目前主要就我一个人在维护这个项目。我也有全职工作和家庭要照顾,所以能投入的时间真的很有限。我是真的很喜欢这个项目,所以才会挤出时间来做。你懂的,生活总是要先解决温饱,然后才能追求爱好。

我会努力在众多建议中挑选一些我觉得不错又可行的功能加到Escrcpy中。虽然我没法立刻实现所有想法,但我会按照自己的节奏慢慢来。希望你能理解。

如果你觉得这个项目对你有帮助,想要它更快发展,我会非常感激你的任何形式的支持。无论是提供代码、改进文档,还是小额赞助,都能帮我投入更多时间在这上面。

再次感谢你的支持和理解。正是因为有像你这样热心的用户,才让我有动力继续改进Escrcpy

**Comment by cruisermaxx** [comment]
感觉文件双向管理功能非常有用呀，现在 escrcpy 只支持文件推送，也就是电脑端到手机端。什么时候可以像 Anlink 一样，支持文件拉取呀，实现手机端到电脑端！

**Comment by viarotel** [comment]
双向文件管理已在计划中。

**Comment by cruisermaxx** [comment]
> 双向文件管理已在计划中。

感谢开发者！非常值得期待~

**Comment by viarotel** [comment]
基于图形化的文件管理器功能已发布，虚拟按键功能说明请参考 https://github.com/viarotel-org/escrcpy/blob/main/README-CN.md#%E8%AE%BE%E5%A4%87%E4%BA%A4%E4%BA%92%E6%8E%A7%E5%88%B6%E6%A0%8F%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%8D%E8%AE%BE%E8%AE%A1%E4%B8%BA%E8%87%AA%E5%8A%A8%E8%B7%9F%E8%B8%AA%E5%90%B8%E9%99%84%E7%9A%84%E6%82%AC%E6%B5%AE%E8%8F%9C%E5%8D%95

**Comment by cruisermaxx** [comment]
> 基于图形化的文件管理器功能已于 v1.23.5+ 发布，虚拟按键功能请参考[说明](https://github.com/viarotel-org/escrcpy/blob/main/README-CN.md#%E8%AE%BE%E5%A4%87%E4%BA%A4%E4%BA%92%E6%8E%A7%E5%88%B6%E6%A0%8F%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%8D%E8%AE%BE%E8%AE%A1%E4%B8%BA%E8%87%AA%E5%8A%A8%E8%B7%9F%E8%B8%AA%E5%90%B8%E9%99%84%E7%9A%84%E6%82%AC%E6%B5%AE%E8%8F%9C%E5%8D%95)

非常感谢开发者，如此高效的更新~非常实用的功能！
