### ISSUE TITLE
Error en FydeOS

### ISSUE THREAD

**Issue by Danielperfull-00** [viarotel-org/escrcpy#214]
![image](https://github.com/user-attachments/assets/ecd03c31-5f8b-4b61-8173-8eec8971b7bf)
Error FydeOS Cuando le doy a Mirror

**Comment by viarotel** [comment]
linux下需要自行安装`scrcpy`作为依赖，是否已正确安装？

**Comment by Danielperfull-00** [comment]
Listo gracias
