### ISSUE TITLE
v1.21.4 镜像画面不显示

### ISSUE THREAD

**Issue by policx** [viarotel-org/escrcpy#216]
应用版本：v1.21.4
运行环境：Windows 11 x64，MIUI14.0.5
触发操作：“开始镜像”连接镜像，电脑屏幕只有一个小方块，鼠标可以控制手机。
![PixPin_2024-07-18_14-35-32](https://github.com/user-attachments/assets/a67c3cc3-b162-454e-9dd6-27fe5bd75cdf)

**Comment by policx** [comment]
重置了，不行

**Comment by viarotel** [comment]
请提供更多信息 是否尝试过其他手机  请尝试使用软件内置的`终端命令`中直接执行 `scrcpy` 查看是否正常

**Comment by policx** [comment]
内置的终端命令中直接执行 scrcpy ，正常

**Comment by viarotel** [comment]
"pbtkucprfqe6rgbe": {
			"--no-video": true,
			"--show-touches": true,
			"--record-format": "mp4"
		}

"--no-video": true,把这个删掉，你似乎修改了单个设备下的配置，所以在全局作用域下重置是没用的，你需要切换到pbtkucprfqe6rgbe设备下关掉禁用视频流，或者直接在配置文件中删掉 --no-video

**Comment by policx** [comment]
** 关掉禁用视频流，完美运行！！！**
