### ISSUE TITLE
反向供网报错

### ISSUE THREAD

**Issue by YunFeng86** [viarotel-org/escrcpy#219]
一加3V ColorOS

报错如下
Exception occurred while executing 'start': java.lang.SecurityException: Permission Denial: starting Intent { act=com.genymobile.gnirehtet.START flg=0x10000000 cmp=com.genymobile.gnirehtet/.GnirehtetActivity mCallingUid=2000 } from null (pid=2467, uid=2000) requires android.permission.WRITE_SECURE_SETTINGS at com.android.server.wm.ActivityTaskSupervisor.checkStartAnyActivityPermission(ActivityTaskSupervisor.java:1270) at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:1220) at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:837) at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1395) at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1341) at com.android.server.am.ActivityManagerService.startActivityAsUserWithFeature(ActivityManagerService.java:3606) at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:730) at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:239) at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97) at android.os.ShellCommand.exec(ShellCommand.java:38) at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:10642) at android.os.Binder.shellCommand(Binder.java:1081) at android.os.Binder.onTransact(Binder.java:901) at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:5267) at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3039) at android.os.Binder.execTransactInternal(Binder.java:1362) at android.os.Binder.execTransact(Binder.java:1288) ,2024-07-27 19:18:14.914 ERROR Main: Execution error: Command C:\Users\Admin\AppData\Local\Programs\Escrcpy\resources\extra\win\android-platform-tools\adb.exe ["-s", "4ccc2600", "shell", "am", "start", "-a", "com.genymobile.gnirehtet.START", "-n", "com.genymobile.gnirehtet/.GnirehtetActivity"] returned with value 255

**Comment by viarotel** [comment]
请尝试直接使用 命令行的方式 执行 gnirehtet 如果依然出现该问题 请向 [gnirehtet](https://github.com/Genymobile/gnirehtet) 反馈问题
