### ISSUE TITLE
可否将电脑的默认音频输入比如电脑上的麦克风，作为手机的音频输入呢~

### ISSUE THREAD

**Issue by yudunning** [viarotel-org/escrcpy#220]
手机的音频可以传输到电脑，用电脑的播放设备播放，那么可否将电脑的默认音频输入比如电脑上的麦克风，作为手机的音频输入呢~   以实现完全用电脑硬件来通过手机通话~

**Comment by yudunning** [comment]
The audio of the mobile phone can be transmitted to the computer and played by the computer's playback device, so can the default audio input of the computer, such as the microphone on the computer, be used as the audio input of the mobile phone~ In order to achieve complete use of computer hardware to make calls through the mobile phone~

**Comment by viarotel** [comment]
需要 `scrcpy` 底层支持，该问题已过时，我将关闭它
