### ISSUE TITLE
【BUG】电脑键盘输入的时候只能输入英文

### ISSUE THREAD

**Issue by AdamTyn** [viarotel-org/escrcpy#221]
附上图片：

<img width="1152" alt="Snipaste_2024-07-31_09-37-14" src="https://github.com/user-attachments/assets/7a234fbf-dfed-49fb-b80c-dfd71b603994">

<img width="576" alt="Snipaste_2024-07-31_09-37-03" src="https://github.com/user-attachments/assets/a841ef27-d0dc-45f3-ada2-fc2c098bf090">

<img width="280" alt="Snipaste_2024-07-31_09-36-43" src="https://github.com/user-attachments/assets/abc8b389-bd57-4656-bbb7-a937ff7cc6e5">

![录制于 2024-07-31 09 34 59 (2)](https://github.com/user-attachments/assets/438ab6ad-527e-4e23-a21b-2f24338bab6b)

**Comment by qianlanggong** [comment]
有同样的困惑

**Comment by qianlanggong** [comment]
![image](https://github.com/user-attachments/assets/ba6d4af4-65c1-4626-94be-46cbf269d48c)试试这样设置

**Comment by wieniawski-lai** [comment]
> ![image](https://private-user-images.githubusercontent.com/107108938/354634798-ba6d4af4-65c1-4626-94be-46cbf269d48c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMDQxODIsIm5iZiI6MTcyNDIwMzg4MiwicGF0aCI6Ii8xMDcxMDg5MzgvMzU0NjM0Nzk4LWJhNmQ0YWY0LTY1YzEtNDYyNi05NGJlLTQ2Y2JmMjY5ZDQ4Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQwMTMxMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YjM5YWE2YWY5MGYyZjM4NTI4YjMyOGFmMDc3NGE3NDk5MmM4ZmY1MjM3OGZjZDZhZDZjZmFjNmIwMmExZjQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.q1tmt4nFk6iSsAMQV_SqaMN4vWPQ0vKCOM5mOFhzCSc)试试这样设置，在偏好设置-输入设置-键盘模式

这样设置之后,仍然是只能输入英文,不能输入中文

**Comment by hanuxxx** [comment]
有同样的问题，只能电脑切换成英文，相当于在设备里直接输入，不能电脑打字输入中文到手机里

**Comment by viarotel** [comment]
该输入是由 `scrcpy` 处理的  我暂时没有找到更好的方式解决中文输入问题

**Comment by izelle** [comment]
也是因为这个原因不能正常输入文字犯愁，目前使用vivo办公套件替代

**Comment by play-big** [comment]
> 该输入是由 `scrcpy` 处理的 我暂时没有找到更好的方式解决中文输入问题

用过几家投屏的，基本上是安装自己的手机输入法来实现；

有一个极限投屏的作者，也是scrcpy，他用的ADB Keyboard，不懂技术，给大佬看看

**Comment by hanuxxx** [comment]
qtscrcpy可以中文输入，用起来挺无感挺顺畅的，不知道是什么方式实现，可以参考~

**Comment by viarotel** [comment]
经最新测试，在偏好设置中将键盘输入方式改为 `UHID` 模式后，然后在安卓设备上找到实体键盘选项（一般路径为，设置 → 系统 → 语言和输入 → 实体键盘）在设备上（一次性）配置键盘布局以匹配计算机的键盘布局后即可输入中文。

需要注意的是：

1. 需要设备输入法对实体键盘支持较好，我采用的是微信输入法（其他输入法应该类似，请自行测试）
2. 在PC上你必须将输入调整为英文状态，这点很重要
3. 你可以通过 `Chrl+ Shift` 快捷键来切换中英文输入

https://github.com/user-attachments/assets/a2f8dfd7-71be-43e8-8570-d8b95fec400c

**Comment by T0NYLau** [comment]
我在用搜狗输入法，是正常没问题的。其他输入法试过不太行
