### ISSUE TITLE
How to fix the lag?

### ISSUE THREAD

**Issue by katastrophe92** [viarotel-org/escrcpy#226]
Hey y'all, i have just one question: How to fix the lag?
Is the same laggy on USB or WIFI connection.
My phone is a Samsung A34 5G, 8Gb RAM and Android 15.
Thank you!

https://github.com/user-attachments/assets/523b9a78-4e0d-4bb2-8b07-add27ea8aa16

**Comment by katastrophe92** [comment]
@viarotel Hi, why closed my issue and what is the fix to my problem?

**Comment by viarotel** [comment]
Hello, I apologize for directly closing your issue. It's important to note that Escrcpy is essentially just a GUI version based on Scrcpy. Therefore, I suggest first trying to improve this issue by adjusting the configuration. If that doesn't solve the problem, I recommend you try scrcpy directly and report the issue to [scrcpy](https://github.com/Genymobile/scrcpy/issues?q=).

**Comment by katastrophe92** [comment]
Hey again. I will try to do this, thanks for the tip
