### ISSUE TITLE
想了解下，手机锁频解锁输密码黑屏有没有办法解决？

### ISSUE THREAD

**Issue by jiangtiger** [viarotel-org/escrcpy#228]
想了解下，手机锁频解锁输密码黑屏有没有办法解决？

**Comment by YumeMichi** [comment]
这个应该是安卓的安全窗口机制，类似银行app无法截图和录像
https://developer.android.com/reference/android/view/WindowManager.LayoutParams#FLAG_SECURE

**Comment by jiangtiger** [comment]
> 这个应该是安卓的安全窗口机制，类似银行app无法截图和录像 https://developer.android.com/reference/android/view/WindowManager.LayoutParams#FLAG_SECURE

了解了，谢谢大佬

**Comment by cruisermaxx** [comment]
qtscrcpy 和 anlink 都是打包 scrcpy的，解锁界面都是正常的。现在突然要盲输，就怪怪的，不能解决吗？

**Comment by YumeMichi** [comment]
> qtscrcpy 和 anlink 都是打包 scrcpy的，解锁界面都是正常的。现在突然要盲输，就怪怪的，不能解决吗？

试了一下你说的qtscrcpy解锁也是一样黑屏的，这是安卓12开始的安全策略。况且黑屏并不影响输入pin或者图案，你依然可以使用键盘输入或者鼠标画图案

**Comment by cruisermaxx** [comment]
> > qtscrcpy 和 anlink 都是打包 scrcpy的，解锁界面都是正常的。现在突然要盲输，就怪怪的，不能解决吗？
> 
> 试了一下你说的qtscrcpy解锁也是一样黑屏的，这是安卓12开始的安全策略。况且黑屏并不影响输入pin或者图案，你依然可以使用键盘输入或者鼠标画图案

谢谢！尝试了一下确实所有基于 scrcpy 的项目都是这样的。画图案太难了，只能用键盘输入pin码容易些了。
另外想请问一下，键盘ctrl+回车，可以映射到app发送消息吗？
用鼠标发消息要不断换到鼠标上。

**Comment by viarotel** [comment]
感谢 @YumeMichi  的热心解答，至于 `映射到app发送消息` 可以手动尝试一下是否可用
