### ISSUE TITLE
可以加一个切换画面黑白的功能吗

### ISSUE THREAD

**Issue by Nirvana-Sun** [viarotel-org/escrcpy#230]
可以加一个切换画面黑白的功能吗，像向日葵远程那种，如果加不了就算了，只是带有色彩的画面不太方便摸鱼，谢谢

**Comment by viarotel** [comment]
很有趣的建议，不过某些国产手机上有类似功能的开关，可以手动开启，需求有些小众，而且因为各厂商实现的接口以及安卓版本问题可能导致不生效，所以暂时不会加入该功能。
