### ISSUE TITLE
请问有什么设置媒体音量的快捷键吗？

### ISSUE THREAD

**Issue by cruisermaxx** [viarotel-org/escrcpy#232]
请问adb连接后，用命令设置媒体音量无效呢？是因为 escrcpy 窗体占用了连接吗？
比如 adb shell media volume --stream 3 --set 0

**Comment by viarotel** [comment]
首先请尝试使用内置的终端，在界面右上角，如果不行的话，请检查命令是否兼容，或者完全关闭escrcpy后测试该命令能够正常工作

**Comment by cruisermaxx** [comment]
这样的 adb 命令无法执行，adb shell 连接不上
![Snipaste_2024-09-10_09-58-23 PC1](https://github.com/user-attachments/assets/e142b6ca-6a2d-41d9-ba6e-83b53cb4d2e2)
