### ISSUE TITLE
feat: 有没有办法做到类似于Android模拟器那样添加按键啊？

### ISSUE THREAD

**Issue by mingshuisheng** [viarotel-org/escrcpy#24]
主要是玩游戏的时候希望可以使用wasd行走之类的。
另外就是Qtcrcpy好像是做到了，不过不知道是怎么做的。
其实如果有思路的话我来做也可以。

**Comment by viarotel** [comment]
[为什么不设计为自动跟踪吸附的悬浮菜单](https://github.com/viarotel-org/escrcpy#设备交互控制栏为什么不设计为自动跟踪吸附的悬浮菜单)
主要是需要做更底层的修改而且可能有性能损失，不过确实有方案，可以参考[electron-scrcpy](https://gitee.com/coutliuxing/electron-scrcpy)

**Comment by mingshuisheng** [comment]
好的，谢谢回复，我去看看。

**Comment by viarotel** [comment]
> [为什么不设计为自动跟踪吸附的悬浮菜单](https://github.com/viarotel-org/escrcpy#设备交互控制栏为什么不设计为自动跟踪吸附的悬浮菜单)
> 主要是需要做更底层的修改而且可能有性能损失，不过确实有方案，可以参考[electron-scrcpy](https://gitee.com/coutliuxing/electron-scrcpy)

好吧，我似乎理解错了，你想要的是[添加对游戏的增强功能，如游戏键位映射](https://github.com/viarotel-org/escrcpy#下一步做什么)
后续有计划添加支持

**Comment by 596142041** [comment]
安卓上面使用什么软件啊
