### ISSUE TITLE
可以把加个设置开启/关闭设备的操作栏附着在镜像窗口下边吗？

### ISSUE THREAD

**Issue by Heanes** [viarotel-org/escrcpy#242]
类似android studio模拟器的效果，这样就比较方便了。
如下：
<img width="480" alt="image" src="https://github.com/user-attachments/assets/4cd4e865-db78-49b2-8e45-9733e89470f6">

**Comment by viarotel** [comment]
参阅该[说明](https://github.com/viarotel-org/escrcpy/blob/main/README-CN.md#%E8%AE%BE%E5%A4%87%E4%BA%A4%E4%BA%92%E6%8E%A7%E5%88%B6%E6%A0%8F%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%8D%E8%AE%BE%E8%AE%A1%E4%B8%BA%E8%87%AA%E5%8A%A8%E8%B7%9F%E8%B8%AA%E5%90%B8%E9%99%84%E7%9A%84%E6%82%AC%E6%B5%AE%E8%8F%9C%E5%8D%95)
