### ISSUE TITLE
关于设备交互控制栏虚浮菜单

### ISSUE THREAD

**Issue by 3364729893** [viarotel-org/escrcpy#243]
https://github.com/viarotel-org/escrcpy/blob/main/README-CN.md#%E8%AE%BE%E5%A4%87%E4%BA%A4%E4%BA%92%E6%8E%A7%E5%88%B6%E6%A0%8F%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%8D%E8%AE%BE%E8%AE%A1%E4%B8%BA%E8%87%AA%E5%8A%A8%E8%B7%9F%E8%B8%AA%E5%90%B8%E9%99%84%E7%9A%84%E6%82%AC%E6%B5%AE%E8%8F%9C%E5%8D%95
如果考虑到不修改Scrcpy 的话，完全可以不做吸附式的，放一个自定义的虚浮菜单（去掉界面其他元素）。目前开启屏幕镜像后，每次操作都要返回的界面操作，而且因为文字的关系，还需要左右滑动。
![image](https://github.com/user-attachments/assets/e62a7e6d-53fc-4548-8570-85fc7c4567e0)

**Comment by viarotel** [comment]
已经在做了可以先预览一下。
![image](https://github.com/user-attachments/assets/faf3943d-b511-4f90-abcf-e282465eb7a2)

**Comment by viarotel** [comment]
![image](https://github.com/user-attachments/assets/b221c3c9-71bd-4b29-99ce-01d3fcd05fe9)

**Comment by 3364729893** [comment]
太厉害了，
![027C6D1C](https://github.com/user-attachments/assets/f81ae3ba-9d7e-4d4a-8b7e-9b446bb9eaad)
![027C7E04](https://github.com/user-attachments/assets/ed8cb719-c064-491f-b7fb-b67336ba98bc)

可以考虑一下自定义的，例如去掉文字说明，改成alt提示文字（鼠标移上去提示），可以竖条，加点其他选项（例如一些快捷键的按钮放上去）

**Comment by viarotel** [comment]
v1.24.0+ 已支持浮动操作栏，注意：该功能不是默认选项需要在 `偏好设置 -> 通用设置 -> 浮动操作栏` 中手动开始

**Comment by viarotel** [comment]
> 太厉害了， ![027C6D1C](https://private-user-images.githubusercontent.com/150577647/366836844-f81ae3ba-9d7e-4d4a-8b7e-9b446bb9eaad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNDQ4NTcsIm5iZiI6MTcyNjE0NDU1NywicGF0aCI6Ii8xNTA1Nzc2NDcvMzY2ODM2ODQ0LWY4MWFlM2JhLTlkN2UtNGQ0YS04YjdlLTliNDQ2YmI5ZWFhZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMlQxMjM1NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMWI5NzdmNmFkY2U4ODhjMjE0MzI5NjQ3NzY5MGRkOTlkMzIyOWI1ZjdiMTYzYmJmNDU5NTU4ZDkwNWI5NTZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YXRk4JmXiqMzQSojo5aN3nuDnE1DhmCzXZD29syifEU) ![027C7E04](https://private-user-images.githubusercontent.com/150577647/366836864-ed8cb719-c064-491f-b7fb-b67336ba98bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNDQ4NTcsIm5iZiI6MTcyNjE0NDU1NywicGF0aCI6Ii8xNTA1Nzc2NDcvMzY2ODM2ODY0LWVkOGNiNzE5LWMwNjQtNDkxZi1iN2ZiLWI2NzMzNmJhOThiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMlQxMjM1NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMzI2YzYyZjJhNjM2NTdmNTllMTgwNDY4MDgyYzY0MTc3NGJmZjU0ZWIxNWU1NGJiMGNlNDFkNzgzOGIzNWRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.J3CdkpJ_HxAP0JniA3WzUYeHojaME_VEg740BZoOvJ4)
> 
> 可以考虑一下自定义的，例如去掉文字说明，改成alt提示文字（鼠标移上去提示），可以竖条，加点其他选项（例如一些快捷键的按钮放上去）

不错的想法，我会考虑你的建议。
