### ISSUE TITLE
请问如何直接用电脑键盘输入文字？

### ISSUE THREAD

**Issue by liyaohaoba** [viarotel-org/escrcpy#247]
在输入控制那里试了下，好像没这个功能额

**Comment by viarotel** [comment]
请参阅 https://github.com/viarotel-org/escrcpy/blob/main/README-CN.md#%E6%97%A0%E6%B3%95%E8%BE%93%E5%85%A5%E4%B8%AD%E6%96%87

**Comment by liyaohaoba** [comment]
可以了 谢谢
