### ISSUE TITLE
中英文切换

### ISSUE THREAD

**Issue by FBIshouxi** [viarotel-org/escrcpy#248]
发现输入时候，中英文切换，按shift, 电脑和手机都会切换中英文， 而且必须是电脑英文， 才能在手机输入，能否在键盘鼠标都是uhid模式且鼠标进入时，阻止案件冒泡？ 不让电脑获取到shift

**Comment by viarotel** [comment]
请使用 Ctrl + Shift 来切换手机上的中英文，目前不支持拦截系统事件

**Comment by FBIshouxi** [comment]
我鼠标键盘都设置的uhid, 按ctrl + shift 不管用。  
我想实现键鼠共享： https://www.bilibili.com/opus/981312813579370501  
目前只能，电脑按ctrl + 空格还原成英文

**Comment by FBIshouxi** [comment]
没事，我手机按shift ,电脑按 ctrl + 空格 改英文

**Comment by FBIshouxi** [comment]
手机使用讯飞输入法就好了， 能调 shift+空格切换中英文
