### ISSUE TITLE
希望可以编辑设备名称及独立配置

### ISSUE THREAD

**Issue by RDsatan** [viarotel-org/escrcpy#25]
如题，实际测试环境可能有多台同型号设备，希望可以支持自定名称，以及对每台设备单独导出配置。
另，直接取当前adb连接未免会造成下次测试时设备配置丢失的问题，可否随配置一同导出？

**Comment by viarotel** [comment]
好的主意 已将该需求列入计划

**Comment by viarotel** [comment]
v1.7.0  已支持为设备添加备注并导入导出配置

**Comment by RDsatan** [comment]
🎉

**Comment by viarotel** [comment]
v1.7.1 增加了对单个设备进行独立配置的功能，欢迎试用 @RDsatan

**Comment by RDsatan** [comment]
> v1.7.1 增加了对单个设备进行独立配置的功能，欢迎试用 @RDsatan

试着自己加了下导出&导入，以及API调用特定功能的能力，请问我可以将这个工具接入我们的测试平台吗？仅仅作为平台能力，不对外开放

**Comment by viarotel** [comment]
@RDsatan 你好，非常感谢你对项目的认可。该软件基于MIT协议，是自由和免费的，你当然可以将其集成到你们的平台中。在此之前，我希望了解一些关于你们的测试平台的详细信息，以便更好地为你提供支持。首先，你提到的测试平台是什么类型的平台？它是在内网还是外网可访问？另外，你是否需要我提供任何支持，例如技术文档、指导或其他帮助？最后，请确保在使用项目源代码时注明作者、联系方式以及著作权信息。非常感谢！

**Comment by RDsatan** [comment]
> @RDsatan 你好，非常感谢你对项目的认可。该软件基于MIT协议，是自由和免费的，你当然可以将其集成到你们的平台中。在此之前，我希望了解一些关于你们的测试平台的详细信息，以便更好地为你提供支持。首先，你提到的测试平台是什么类型的平台？它是在内网还是外网可访问？另外，你是否需要我提供任何支持，例如技术文档、指导或其他帮助？最后，请确保在使用项目源代码时注明作者、联系方式以及著作权信息。非常感谢！

当然，我会标注清楚项目原地址以及作者信息。为了实现安卓测试场景自动化，我们需要相关的测试能力，scrcpy是最优选择。这个工具的特性使得它很适合被改造为API调用的平台，完全可以基于此工具为中转远程调用scrcpy能力来实现如远程录屏、执行脚本等操作。非常棒的工具！

**Comment by RDsatan** [comment]
其实最关键的还是在于能够远程调用相关功能来实现远程操控手机，这一点真的非常重要。经过改造测试，escrcpy的功能完全符合预期，后续计划基于此项目进行测试的开发，当然，仅内网使用。再次感谢！
