### ISSUE TITLE
MIUI下的多屏协同

### ISSUE THREAD

**Issue by LeviHonestus** [viarotel-org/escrcpy#250]
[【scrcpy】Android 11下的多窗口应用投屏/桌面模式投屏](https://www.bilibili.com/video/BV1dL41137f6)

多屏协同在类原生下体验良好，MIUI下似乎有问题，参考上面的视频可以这样做：

1. 打开多屏协同，这时无显示
2. adb shell am stack list 
获取应用<STACK_ID>，前台应用是列表第一个
3. adb shell am display move-stack <STACK_ID> <DISPLAY_ID>
把应用推到虚拟屏幕，然后就能显示了
（手机上如果打开 强制使用桌面模式 ，应用是小窗形式，关闭后正常）

可以的话，希望添加一键开启多屏协同、获取前台应用ID并推到虚拟屏幕的按钮

软件版本：1.24.2-win-setup-x64
手机型号：Redmi Note 11T Pro
手机系统：MIUI 14.0.7

**Comment by 258692011** [comment]
一样的问题，小米10 pro 安卓13，不支持多屏协同
