### ISSUE TITLE
便携版仍然会在c盘下产生配置文件

### ISSUE THREAD

**Issue by lsdxfs** [viarotel-org/escrcpy#252]
个人测试到的会在c盘下 C:\Users\123\AppData\Roaming 产生文件
删除后之前的设置消失

私以为便携版软件指的是可以在多设备间无缝切换 所以便携版软件应该实现配置和软件文件走? 一般便携软件配置文件夹和.exe程序一般位于同一文件夹下

**Comment by lsdxfs** [comment]
补充 测试过 
Escrcpy-1.24.2-win-x64.zip 和  Escrcpy-1.24.2-win-portable-x64.exe 
方式为
打开软件 设置为繁体中文 关闭软件 删除C:\Users\123\AppData\Roaming下escrcpy文件夹 再次打开软件之前的设置丢失

**Comment by viarotel** [comment]
感谢您的反馈。我理解您对配置文件存储位置的考虑。采用目前的方案有主要以下原因:

1. 防止软件自更新时导致配置丢失
3. 适配多平台，遵循各操作系统的推荐做法

为了平衡便携性和稳定性, Escrcpy 提供了导出和导入配置的功能。这应该能在一定程度上满足您的需求。
