### ISSUE TITLE
目前测试到的一个问题

### ISSUE THREAD

**Issue by weiDpang** [viarotel-org/escrcpy#253]
目前先通过USB连接手机后，再开启无线模式
断开USB连接后，确实可以通过局域网WiFi控制手机
但问题是，当手机重启后，手机IP地址并没有变的情况下，电脑通过WiFi已经无法再连接
如果想要再次通过WiFi连接手机，只能再通过USB连接开启无线模式，确实麻烦
真的强烈希望可以解决一下这个问题
不然每次都要先通过USB连接后开发无线模式，真的不太方便，
希望可以通过手机脚本或者其它的方式，解决这个问题，麻烦了

**Comment by viarotel** [comment]
受制于安卓的安全限制，你可能需要借助 https://github.com/RikkaApps/WADB 类似软件进行解决
