### ISSUE TITLE
开始镜像报错

### ISSUE THREAD

**Issue by zhou-le** [viarotel-org/escrcpy#255]
ERROR: CreateProcessW() error 2 ERRO,R: Command not found: [C:\Users\����\AppData\Local\Temp\2m94MIGtsciZj4Syu821iUhpKed\resources\extra\win\android-platform-tools\adb.exe], [start-server] ERROR: (make 'adb' accessible from your PATH or define its fullpath in the ADB environment variable) ERROR: Could not execute "adb start-server" ERROR: Could not start adb server ,ERROR: Server connection failed
![微信截图_20241016130442](https://github.com/user-attachments/assets/4c65cb17-e85d-465b-86fd-2304d6e6128b)

但是下方操作是可行的，比如加减音量，截取屏幕

**Comment by zhou-le** [comment]
我尝试将adb.exe所在目录复制到没有中文的路径中，然后将更改后的路径添加到环境变量中，问题解决
![微信图片_20241016133010](https://github.com/user-attachments/assets/6892e498-fb8d-4318-a357-b49ed61e02a8)

**Comment by 377343577** [comment]
作者您好，请教一个问题我使用escrcpy v1.22.4连接到手机后无法打开镜像错误显示为
![QQ_1736091277895](https://github.com/user-attachments/assets/25fd9d7f-1b3b-49a0-91de-bfba25955d1f)
但是我使用escrcpy v1.28.3版本连接手机可以正常打开镜像。
请教您这个问题是因为我在自己的代码里面运行py-scrcpy的时候报错为 Video stream is disconnected。
