### ISSUE TITLE
功能请求：增加屏幕开关快捷按钮

### ISSUE THREAD

**Issue by Typhonling** [viarotel-org/escrcpy#262]
很久以前在别的地方提过但没开issue，因为这个原因一直停留在Qtscrcpy。

很多情况下，镜像时是需要不时拿起手机来使用的，只使用scrcpy快捷键按显得有些麻烦，镜像使用频率不高时还容易忘记快捷键。

具体请求是将以下两个快捷键做成一个按钮加入到交互栏中。 

 | Action                                      |   Shortcut
 | ------------------------------------------- |:-----------------------------
 | Turn device screen off (keep mirroring)     | <kbd>MOD</kbd>+<kbd>o</kbd>
 | Turn device screen on                       | <kbd>MOD</kbd>+<kbd>Shift</kbd>+<kbd>o</kbd>

#225
 #82
#75

**Comment by viarotel** [comment]
感谢你反馈，最近确实很多人提过这个问题，我会尝试这样做

**Comment by viarotel** [comment]
在 v1.25.1 中我实验性添加了关闭屏幕按钮，需要注意的是，由于 scrcpy 没有提供静默的API调用方式，Escrcpy 将不得不启动一个 EscrcpyHelper 窗口来保证其可用性，关闭该窗口将回退到关闭之前的状态（我确实尝试了很多其他的方法例如： adb命令，执行 .dex 文件的方式，依然达不到 scrcpy的效果，所以这是目前最可靠的方案，或者如果你有更好的方法请告诉我，谢谢）

**Comment by Typhonling** [comment]
感谢更新，虽然使用起来有点奇怪（没有亮屏按钮，需要通过关闭 EscrcpyHelper 窗口来实现亮屏功能）。于我来说能用就行，方便多了，不需要手动电源键锁屏再解锁亮屏了。
