### ISSUE TITLE
升级 macos15.01后，启动报错 “Escrcpy”意外退出。

### ISSUE THREAD

**Issue by neilpan813** [viarotel-org/escrcpy#264]
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Incident Identifier: BD629372-39DF-40C3-AF61-C22AD6E73D45
CrashReporter Key:   0C960282-32E7-6CDC-B514-84F6BA858A92
Hardware Model:      MacBookPro15,4
Process:             Escrcpy [8572]
Path:                /Applications/Escrcpy.app/Contents/MacOS/Escrcpy
Identifier:          org.viarotel.escrcpy
Version:             1.24.3 (1.24.3)
Code Type:           X86-64 (Native)
Role:                Default
Parent Process:      launchd [1]
Coalition:           org.viarotel.escrcpy [4272]

Date/Time:           2024-10-27 09:24:49.0738 +0800
Launch Time:         2024-10-27 09:24:49.0510 +0800
OS Version:          macOS 15.0.1 (24A348)
Release Type:        User
Report Version:      104

Exception Type:  EXC_CRASH (SIGKILL (Code Signature Invalid))
Exception Codes: 0x0000000000000000, 0x0000000000000000
Termination Reason: CODESIGNING 4 Launch Constraint Violation

Triggered by Thread:  0

Thread 0 Crashed:
0   dyld_path_missing             	       0x1178f6000 _dyld_start + 0
1   ???                           	               0x1 ???

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ff7b43f6be0
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x00000001178f6000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000 
Trap Number:     0

Binary Images:
       0x1178f1000 -        0x11797dfff dyld_path_missing (*) <69c73748-37ae-3a6f-83af-690645c3da75> /dyld_path_missing
       0x10bb09000 -        0x10bb0afff main_executable_path_missing (*) <4c4c4425-5555-3144-a1b6-274ddc211623> /main_executable_path_missing
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

Error Formulating Crash Report:
dyld_process_snapshot_get_shared_cache failed

EOF

-----------
Full Report
-----------

{"app_name":"Escrcpy","timestamp":"2024-10-27 09:24:49.00 +0800","app_version":"1.24.3","slice_uuid":"4c4c4425-5555-3144-a1b6-274ddc211623","build_version":"1.24.3","platform":0,"bundleID":"org.viarotel.escrcpy","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 15.0.1 (24A348)","roots_installed":0,"name":"Escrcpy","incident_id":"BD629372-39DF-40C3-AF61-C22AD6E73D45"}
{
  "uptime" : 23000,
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro15,4",
  "coalitionID" : 4272,
  "osVersion" : {
    "train" : "macOS 15.0.1",
    "build" : "24A348",
    "releaseType" : "User"
  },
  "captureTime" : "2024-10-27 09:24:49.0738 +0800",
  "codeSigningMonitor" : 0,
  "incident" : "BD629372-39DF-40C3-AF61-C22AD6E73D45",
  "pid" : 8572,
  "cpuType" : "X86-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2024-10-27 09:24:49.0510 +0800",
  "procStartAbsTime" : 23007009585104,
  "procExitAbsTime" : 23007031538894,
  "procName" : "Escrcpy",
  "procPath" : "\/Applications\/Escrcpy.app\/Contents\/MacOS\/Escrcpy",
  "bundleInfo" : {"CFBundleShortVersionString":"1.24.3","CFBundleVersion":"1.24.3","CFBundleIdentifier":"org.viarotel.escrcpy"},
  "storeInfo" : {"deviceIdentifierForVendor":"2C27D618-0CD2-5D87-865B-A096682A8A4B","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "org.viarotel.escrcpy",
  "crashReporterKey" : "0C960282-32E7-6CDC-B514-84F6BA858A92",
  "lowPowerMode" : 1,
  "codeSigningID" : "",
  "codeSigningTeamID" : "",
  "codeSigningFlags" : 16777216,
  "codeSigningValidationCategory" : 0,
  "codeSigningTrustLevel" : 4294967295,
  "bootSessionUUID" : "9914FACC-430A-40DA-B54D-83B13F9089A2",
  "wakeTime" : 1017,
  "bridgeVersion" : {"build":"22P353","train":"9.0"},
  "sleepWakeUUID" : "929C73FF-8404-4A3B-BB09-8CFC5BD70D8F",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGKILL (Code Signature Invalid)"},
  "termination" : {"flags":66,"code":4,"namespace":"CODESIGNING","indicator":"Launch Constraint Violation"},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":287541,"threadState":{"r13":{"value":0},"rax":{"value":0},"rflags":{"value":512},"cpu":{"value":0},"r14":{"value":0},"rsi":{"value":0},"r8":{"value":0},"cr2":{"value":0},"rdx":{"value":0},"r10":{"value":0},"r9":{"value":0},"r15":{"value":0},"rbx":{"value":0},"trap":{"value":0},"err":{"value":0},"r11":{"value":0},"rip":{"value":4690239488,"matchesCrashFrame":1},"rbp":{"value":0},"rsp":{"value":140701857704928},"r12":{"value":0},"rcx":{"value":0},"flavor":"x86_THREAD_STATE","rdi":{"value":0}},"frames":[{"imageOffset":20480,"symbol":"_dyld_start","symbolLocation":0,"imageIndex":0},{"imageOffset":1,"imageIndex":2}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4690219008,
    "size" : 577536,
    "uuid" : "69c73748-37ae-3a6f-83af-690645c3da75",
    "path" : "\/dyld_path_missing",
    "name" : "dyld_path_missing"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4491087872,
    "size" : 8192,
    "uuid" : "4c4c4425-5555-3144-a1b6-274ddc211623",
    "path" : "\/main_executable_path_missing",
    "name" : "main_executable_path_missing"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "vmSummary" : "ReadOnly portion of Libraries: Total=868K resident=0K(0%) swapped_out_or_unallocated=868K(100%)\nWritable regions: Total=8200K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8200K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8192K        1 \nVM_ALLOCATE                          4K        1 \n__DATA                              16K        3 \n__DATA_CONST                        28K        2 \n__DATA_DIRTY                         8K        2 \n__LINKEDIT                         308K        3 \n__TEXT                             572K        2 \n__TPRO_CONST                       276K        1 \nmapped file                        4.3G       24 \nshared memory                        8K        2 \n===========                     =======  ======= \nTOTAL                              4.4G       42 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "logWritingSignature" : "22434fb11da7903ce653ba86ca2e35ac456e6769",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "6246d6a916a70b047e454124",
      "factorPackIds" : {

      },
      "deploymentId" : 240000010
    },
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "45f4e2a5-551b-4bc2-a2dc-19c244dda8f8",
      "experimentId" : "6643969b3099cf28e049862f",
      "deploymentId" : 400000007
    }
  ]
},
  "reportNotes" : [
  "dyld_process_snapshot_get_shared_cache failed"
]
}

Model: MacBookPro15,4, BootROM 2069.0.0.0.0 (iBridge: 22.16.10353.0.0,0), 4 processors, Quad-Core Intel Core i5, 1.4 GHz, 16 GB, SMC 
Graphics: Intel Iris Plus Graphics 645, Intel Iris Plus Graphics 645, Built-In
Display: Color LCD, 2560 x 1600 Retina, Main, MirrorOff, Online
Memory Module: BANK 0/ChannelA-DIMM0, 8 GB, LPDDR3, 2133 MHz, SK Hynix, H9CCNNNCLGALAR-NVD
Memory Module: BANK 2/ChannelB-DIMM0, 8 GB, LPDDR3, 2133 MHz, SK Hynix, H9CCNNNCLGALAR-NVD
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x870), wl0: Jul 26 2024 20:45:01 version 16.20.380.0.3.6.130 FWID 01-c866e60e
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: T2Bus
USB Device: Touch Bar Backlight
USB Device: Touch Bar Display
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Headset
USB Device: Ambient Light Sensor
USB Device: FaceTime HD Camera (Built-in)
USB Device: Apple T2 Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 63.5

**Comment by neilpan813** [comment]
有可能是adb需要升级，尝试中。

**Comment by viarotel** [comment]
请更新到 v1.25.1+ 查看是否解决问题，要注意的是请安装对应架构的安装包

**Comment by neilpan813** [comment]
确认解决，之前一直用的是Escrcpy-1.25.1-mac-universal.dmg ，更换对应的Escrcpy-1.25.2-mac-x64.dmg 安装包 得以解决。感谢
