### ISSUE TITLE
可以把刷新改成静默刷新吗，我在操作其他按钮页面一闪一闪的好奇怪

### ISSUE THREAD

**Issue by 87074139** [viarotel-org/escrcpy#268]

**Comment by viarotel** [comment]
我刚刚发布了一个新的版本，优化了你所说的刷新问题，请更新后尝试。

**Comment by 87074139** [comment]
我下载的macos 最新的通用版本问题依然存在 我在浏览手机文件时页面会自动刷新

**Comment by 87074139** [comment]
而且刷新的时候他尽然是先删除原来的数据在插入新的，这不科学啊 数据不应该是双向绑定的吗 怎么会抖一下呢

**Comment by 87074139** [comment]
刷新应该是无感刷新

**Comment by viarotel** [comment]
很抱歉我没有 macOS 可以测试，如果可以请提供视频，以便让我进行判断问题

**Comment by viarotel** [comment]
你可以使用对应你架构的版本而不是通用版本尝试有无该问题

**Comment by 87074139** [comment]
我使用的是1.25.3 他后台会有一个自动刷新线程导致我在操作其他功能的时候界面会被重绘

**Comment by viarotel** [comment]
你是 x64 还 arm64 平台，请尝试对应架构的安装包 而不是通用版本
