### ISSUE TITLE
Recording stability

### ISSUE THREAD

**Issue by viarotel** [viarotel-org/escrcpy#270]
Hey, this version works perfectly as intended!!! Thank you so much!!

Some things I noticed:
1. If "Turn Off at End Screen" is ON then camera recording is not working. Even if you disable it recording won't start. We then 
have to use "Reset to Default" to reset  "Turn Off at End Screen" to close error.

2. Recording orientation is not working. I have tried to change video direction to 180 but it didnt work.

_Originally posted by @xM0DI in https://github.com/viarotel-org/escrcpy/issues/263#issuecomment-2443496911_

**Comment by xM0DI** [comment]
Just updated to latest version. The video direction setting in Recording tab is not affecting Camera recording. It only works for screen mirror recording.
I am currently using --orientation=180 to get a forced rotation in Camera recording but then Screen mirroring is flipped.
