### ISSUE TITLE
[Feature Request] Change title of window based on actions.

### ISSUE THREAD

**Issue by xM0DI** [viarotel-org/escrcpy#271]
If possible can we add action name in title? 
For eg.
When we lauch Screen Mirror it can show Show Device ID / Model name followed by ScreenMirror mention in title.
![image](https://github.com/user-attachments/assets/faabc39e-f989-4a9b-98a7-c48b9ba55e4f)

or 

When camera is launched from Escrcpy menu it can mention which camera is used or it can just show camera.
![image](https://github.com/user-attachments/assets/b97411a6-1046-484d-b874-0da23ebf97c4)

This might help user who want to use window capture in OBS to automatically select window based on title.

This change might also be implemented in recording names as it will help to sort saved recording based on names mention on recording files.
Thank You!!

**Comment by viarotel** [comment]
I would consider doing that

**Comment by xM0DI** [comment]
This version works!!! thank you!
