### ISSUE TITLE
[Bug] 播放音频沙哑

### ISSUE THREAD

**Issue by kayuml** [viarotel-org/escrcpy#272]
存在一异常bug，安装后时日稍久，镜像播放音频即显沙哑/电音，无线调试与USB调试皆遇此况。
尝试: 多台未装此软件的新电脑，安装后经几个月，亦现此问题。
版本: v1.25.3最新版，以前版本也存在此问题
注: 所有设备第一次安装时播放音频正常

**Comment by viarotel** [comment]
请测试仅使用命令行版本的 scrcpy 是否有该问题，escrcpy 只是提供了 GUI集成 底层音频转发仍然由 scrcpy实现，所以理论上 escrcpy不会引起上述问题
