### ISSUE TITLE
当我进行【关闭屏幕】操作时，出现黑色小窗

### ISSUE THREAD

**Issue by jonilchan** [viarotel-org/escrcpy#279]
当我进行【关闭屏幕】操作时，出现黑色小窗。希望不出现新的小窗

![image](https://github.com/user-attachments/assets/82eb8e9d-2199-4b72-8604-b075bf99ec90)

**Comment by gdzjy** [comment]
还是用快捷键Alt+O 吧 

@viarotel  用发送快捷键方式，是不是可以隐藏这个黑色小窗呢？

**Comment by viarotel** [comment]
试过了，如果不打开窗口，快捷键时没有效果的。

**Comment by gdzjy** [comment]
> 试过了，如果不打开窗口，快捷键时没有效果的。
@viarotel 

小米手机用参数： --turn-screen-off  也有效。如图设置后投屏手机就自动黑屏了。
![PixPin_2024-11-06_19-05-07](https://github.com/user-attachments/assets/d07c876c-45db-473d-acc3-1c29ddcf12bf)

**Comment by apples1949** [comment]
点关闭屏幕的实际效果是实机黑屏。镜像屏幕不受影响
