### ISSUE TITLE
当我后台有别的ADB在运行时，该软件无法正常识别手机

### ISSUE THREAD

**Issue by jonilchan** [viarotel-org/escrcpy#280]
我打开android studio这种软件时，无法进行usb设备的搜索，无法打开镜像。希望可以修复该问题，无论什么时候都使用内置的adb

**Comment by viarotel** [comment]
或许我可以添加一个新的选项:使用内置adb，来解决该问题，晚些时候我会添加该选项。发自我的 iPhone在 2024年11月5日，20:34，Jonil ***@***.***> 写道：﻿
我打开android studio这种软件时，无法进行usb设备的搜索，无法打开镜像。希望可以修复该问题，无论什么时候都使用内置的adb

**Comment by jonilchan** [comment]
十分感谢

**Comment by viarotel** [comment]
请问你的系统是什么，我将为你编译一个测试版本

**Comment by jonilchan** [comment]
> 请问你的系统是什么，我将为你编译一个测试版本

windows amd64 感谢

**Comment by viarotel** [comment]
请提供你的邮箱，GitHub有附件限制

**Comment by jonilchan** [comment]
> 请提供你的邮箱，GitHub有附件限制

jonilchan@foxmail.com
