### ISSUE TITLE
优化用户体验建议。

### ISSUE THREAD

**Issue by gdzjy** [viarotel-org/escrcpy#281]
**1，镜像投屏界面希望增加顶部/侧边吸附功能，类似于QQ。**

**2，操控栏悬浮可以设置只显示需要的功能（目前是一长串 操作并不友好），并可以调整吸附在镜像窗口的指定位置（本人更愿意放在标题栏中，这样投屏界面整洁、方便操作，效果如图）。**
![PixPin_2024-11-06_14-11-23](https://github.com/user-attachments/assets/5ede0f87-febc-4a33-8e73-15ef82bb6a18)

**3，关闭屏幕功能不显示小窗口。**

**4，无线连接设备可以设置快捷方式（设置好IP和端口的快捷方式，点击一键链接）或记录历史记录（如图）：**
![PixPin_2024-11-06_14-17-20](https://github.com/user-attachments/assets/03186ccf-4351-492e-9aa1-b512bc15b599)

**Comment by viarotel** [comment]
你的想法非常不错，不过遗憾的是在不修改原版scrcpy的前提下，我们暂时只能做到第4点，我会花时间去优化设备连接体验，请期待。

**Comment by gdzjy** [comment]
> 你的想法非常不错，不过遗憾的是在不修改原版scrcpy的前提下，我们暂时只能做到第4点，我会花时间去优化设备连接体验，请期待。

好的，我以为都是UI可以修改的功能。

**Comment by viarotel** [comment]
> 建议窗口可以贴边自动收缩，类似QQ的那种，这样更实用方便了

贴边自动隐藏功能已发布
