### ISSUE TITLE
[建议/bug] 关于启动应用的相关建议/自动旋转屏幕问题

### ISSUE THREAD

**Issue by apples1949** [viarotel-org/escrcpy#286]
![image](https://github.com/user-attachments/assets/b950dd4b-e24f-4260-8863-4dd5fbcd815c)
如图，可以在应用列表上可以增加一行文本框，根据输入的文本进行快速筛选应用

BUG：
https://github.com/user-attachments/assets/f504a4c5-c1ec-429d-86a8-9f18a06d74db
点击开始镜像，初始竖屏，进入强制横屏应用。出现触碰点与鼠标位置对应不上，但鼠标实际上还是能正确点击实际位置。直接选择强制横屏的应用打开镜像。不会自动旋转。且不会显示触碰点。完成以上行为后，不论横屏还是竖屏。必定出现触碰点与鼠标位置对应不上的情况。只能尝试重新打开镜像进行恢复。

手机型号：荣耀200Pro

**Comment by viarotel** [comment]
v1.26.3+已加入检索应用程序，旋转问题需要scrcpy解决

**Comment by apples1949** [comment]
补充一个bug
单独打开强制亮屏的应用，会市区强制亮屏的效果

**Comment by apples1949** [comment]
后续反馈，新版本引用的scrcpyv3已解决屏幕旋转问题。问题解决。

**Comment by weizheyang** [comment]
> v1.26.3+已加入检索应用程序，旋转问题需要scrcpy解决

请问通过“启动APP”方式打开应用时，如何使APP横屏显示？旋转屏幕可以修改手机设置与镜像，并不会影响“启动APP”的方式
![image](https://github.com/user-attachments/assets/137e7d2b-7f0c-4d06-bedf-925c82b458b7)
