### ISSUE TITLE
无线连接，如果连接不上，等待过程时间太长。能不能增加一个手动中途中断的按钮

### ISSUE THREAD

**Issue by cruisermaxx** [viarotel-org/escrcpy#288]
无线连接有时候需要发起第二次才能连接上，如果第一次连接不上，等待过程时间太长。
能不能增加一个手动中途中断的按钮，方便更快地手动发起第二次连接。
谢谢！
![PC1 Snipaste_2024-11-07_16-12-16](https://github.com/user-attachments/assets/59989325-57ab-47fe-8c82-f4a0083045b3)

**Comment by viarotel** [comment]
v1.26.3+已加入

**Comment by cruisermaxx** [comment]
> v1.26.3+已加入

真是很棒的更新

**Comment by cruisermaxx** [comment]
> v1.26.3+已加入

可能还有个小问题，就是连接之后，设备列表能不能自动刷新一次呢？现在还需要手动点击刷新一次。
