### ISSUE TITLE
[Bug] Using --video-buffer will not make it launch

### ISSUE THREAD

**Issue by DWolf19** [viarotel-org/escrcpy#291]
esrcpy v1.26.2
scrcpy v2.7
Android Debug Bridge version 1.0.41
Version 35.0.2-12147458
Running on Windows 10.0.19045

When changing --video-buffer to --display-buffer in config.json it will run
Test it on scrcpy

**Comment by viarotel** [comment]
The next version of scrcpy will be adjusted. For details, see https://github.com/Genymobile/scrcpy/pull/5420
In order to implement the start APP function, I integrated the next version of scrcpy in v1.26.2 in advance
But you don’t seem to use the built-in scrcpy of escrcpy, so this problem occurs?

**Comment by viarotel** [comment]
Ok sorry, I tested it and the --video-buffer option doesn't seem to work in the start APP. I don't want to adjust it back and forth. I think you can temporarily solve your current problem by adding scrcpy parameters.

**Comment by viarotel** [comment]
You just need to press the Alt key to move the mouse

**Comment by viarotel** [comment]
Well, the option was rolled back in v.1.26.3, and now there should be no error, and the issue is over
