### ISSUE TITLE
[Help] 如何禁用鼠标悬浮？

### ISSUE THREAD

**Issue by wuerbuzuo** [viarotel-org/escrcpy#293]
鼠标悬浮在某些场景下会出现操作问题，请问该如何禁用？对应scrcpy的命令是--no-mouse-hover

这是禁用鼠标悬浮的效果
![1](https://github.com/user-attachments/assets/87d5db04-c12e-4ddf-89d6-30eb0c760280)

这是escrcpy的效果：
![2](https://github.com/user-attachments/assets/115171b5-1f0c-4eee-81c3-67ffd303ce1d)

**Comment by viarotel** [comment]
在偏好设置中设置附加 scrcpy命令

**Comment by wuerbuzuo** [comment]
> 在偏好设置中设置附加 scrcpy命令

看到了 谢谢
