### ISSUE TITLE
[Help] 我犯了中文目录的低级错误，希望能分享给大家

### ISSUE THREAD

**Issue by TAKAYANORIKO** [viarotel-org/escrcpy#296]
我将程序安装在中文目录下，导致无法开启镜像，无法关闭屏幕，其他功能都是正常的，部分日志如下。
[2024-11-15 22:39:46.962] [error] scrcpyProcess.stderr.data: ERROR: CreateProcessW() error 2
ERROR: Command not found: [D:\    \Escrcpy\resources\extra\win\android-platform-tools\adb.exe], [start-server]
ERROR: (make 'adb' accessible from your PATH or define its fullpath in the ADB environment variable)
ERROR: Could not execute "adb start-server"
ERROR: Could not start adb server

经过各种尝试后才发现是中文目录这种低级错误。作者老师或许可以把这条提示放在“常见问题”里？相信很多用户小白也会遇到类似问题的。谢谢！

**Comment by viarotel** [comment]
已置顶该问题
