### ISSUE TITLE
有个小问题，就是连接之后，设备列表能不能自动刷新一次呢？现在还需要手动点击刷新一次。

### ISSUE THREAD

**Issue by cruisermaxx** [viarotel-org/escrcpy#297]
如题，之前的打断连接已实现，就是连接成功后能不能自动刷新列表。
还有设备断开wifi或者离开路由器，也自动刷新，自动保持列表为最新？

这是之前的 issue 已解决，在此基础上做了一些补充回复。
https://github.com/viarotel-org/escrcpy/issues/288

**Comment by viarotel** [comment]
其实我已经添加了自动刷新，只是在某些情况下不生效，所以我才加入手动刷新的按钮，已保证其稳定性。

**Comment by cruisermaxx** [comment]
> 其实我已经添加了自动刷新，只是在某些情况下不生效，所以我才加入手动刷新的按钮，以保证其稳定性。

很奇怪的是，自动刷新我在任何情况下都未见其生效，感觉完全被阻止了，不知是啥原因？

**Comment by viarotel** [comment]
我晚些时间去排查一下

**Comment by cruisermaxx** [comment]
> 我晚些时间去排查一下

好的，主要是wifi无线连接的问题

**Comment by viarotel** [comment]
该问题已在v1.27.3+中进行了优化
