### ISSUE TITLE
能再提一个任务栏托盘区图标的问题吗？最小化之后不能直接收起到隐藏区域

### ISSUE THREAD

**Issue by cruisermaxx** [viarotel-org/escrcpy#298]
Windows10 操作系统下，点击关闭按钮之后，托盘区图标先是收起到非隐藏区域，然后点击小三角，才能收起到隐藏区域。
和微信、qq这种直接收起效果差一点，多几步操作有点不方便？
请问能检查一下吗？感谢！

![PC1 Snipaste_2024-11-19_15-21-11](https://github.com/user-attachments/assets/86ddecea-fed3-4c42-9620-086858f80f5a)

![PC1 Snipaste_2024-11-19_15-21-21](https://github.com/user-attachments/assets/b0a21cac-2dde-4bcf-bde9-3d9a9fbc500a)

**Comment by viarotel** [comment]
这是windows的默认行为，你可以点击小三角后将escrcpy图标拖到外边，这是一次性操作发自我的 iPhone在 2024年11月19日，17:31，Henry ***@***.***> 写道：﻿
点击关闭按钮之后，托盘区图标先是收起到非隐藏区域，然后点击小三角，才能收起到隐藏区域。
和微信、qq这种直接收起效果差一点，多几步操作有点不方便？
请问能检查一下吗？感谢！
PC1.Snipaste_2024-11-19_15-21-11.png (view on web)
PC1.Snipaste_2024-11-19_15-21-21.png (view on web)

**Comment by cruisermaxx** [comment]
但是 Windows 常见的大多数应用都没有这个问题，拖放一次到隐藏区域之后，就会一直自动到隐藏区域。
而 Escrcpy 重启下次打开程序后，原来的设置又失效了，还要再次拖放，实在是不方便。

**Comment by viarotel** [comment]
我使用 windows 11 只需要一次性设置，没有遇到你说的问题，或者你可以在windows任务栏设置中手动强制允许Escrcpy图标展示
