### ISSUE TITLE
能否将相机作为Windows相机使用，使微信等视频通话可以调用手机相机

### ISSUE THREAD

**Issue by 18801121535** [viarotel-org/escrcpy#301]
#### Describe the problem you confuse
目前可以连接手机的相机，能否增加一个作为Windows相机的功能，不知道这个难度大不大

**Comment by viarotel** [comment]
该功能较难实现，需要操作系统提供相关API，并且scrcpy也需要显式支持该功能，Escrcpy原则上只是提供了对scrcpy的GUI支持
