### ISSUE TITLE
[Feature Request] Add a Button to Directly Open Terminal with ADB Shell

### ISSUE THREAD

**Issue by f870103** [viarotel-org/escrcpy#304]
Currently, running adb shell requires opening a separate terminal and manually typing the command. This process can be repetitive and time-consuming, especially for users who frequently execute ADB shell commands during device management or testing.

## Describe the solution you'd like
Add a button to the main UI (as shown in the attached concept screenshot) that directly executes the adb shell command for the specified device.

Clicking this button should open a terminal session for the selected device, providing immediate access to the Android shell.

![adb shell](https://github.com/user-attachments/assets/d32d638e-9023-45c3-b463-b72246e42ba6)

**Comment by viarotel** [comment]
This feature has been optimized in v1.27.3
