### ISSUE TITLE
[BUG] turn off screen doesnt work on version v1.27.1

### ISSUE THREAD

**Issue by aenold** [viarotel-org/escrcpy#305]
turn off screen feature doesnt work anymore on windows 11, please fix it

**Comment by viarotel** [comment]
I didn't encounter this problem, is there any error message?

**Comment by aenold** [comment]
no, there is no error message , when I connect the device and click the turn off screen button , it doesnt turn off the screen but the same button works on version 1.27.0 . I checked the option when the device is connected it would turn off the screen, it doesnt work in version 1.27.1 as well but works on 1.27.0
