### ISSUE TITLE
[Bug] Startup Camera and Record Camera not working in this version!

### ISSUE THREAD

**Issue by xM0DI** [viarotel-org/escrcpy#306]
As title says, Both camera related options are broken or not working.

**Comment by viarotel** [comment]
I haven't encountered this problem, is there any error?

**Comment by xM0DI** [comment]
So this is working on android 13+ phones but does no support Android 12 or below it. 

Error is shown when Android 12 phone is connected:
![image](https://github.com/user-attachments/assets/d64c7092-a8a4-4001-a254-d47a83de749b)

**Comment by viarotel** [comment]
Maybe you need to report the problem to scrcpy

**Comment by xM0DI** [comment]
yep yes I will raise issue in Scrcpy [https://github.com/Genymobile/scrcpy/issues/5539#issue-2693268662](url)

**Comment by xM0DI** [comment]
Just an update:
The bug might be solved in 3.0.1 version.
If interested here are details: [5539](https://github.com/Genymobile/scrcpy/issues/5539#issuecomment-2514129156)
