### ISSUE TITLE
[Help] 如何在应用发生屏幕保护，黑屏时，保持鼠标点击？

### ISSUE THREAD

**Issue by wuerbuzuo** [viarotel-org/escrcpy#308]
如下图所示，app禁止截图，所以显示是黑屏，这种情况下scrcpy是可以点击和滑动的，但是escrcpy不能做点击和滑动，请问该如何设置？
![PixPin_2024-11-26_09-32-42](https://github.com/user-attachments/assets/fd2655e1-063b-4e1c-943d-75502284f9d9)

**Comment by apples1949** [comment]
黑屏为app保护措施。大概率无法解决。建议洗洗睡吧。
