### ISSUE TITLE
[Bug] v1.27.1: Bad CPU type in executable

### ISSUE THREAD

**Issue by QQ4OU** [viarotel-org/escrcpy#311]
#### Describe the bug
1.27.1
/Applications/Escrcpy.app/Contents/Resources/extra/mac/scrcpy/scrcpy: line 6: ./scrcpy_bin: Bad CPU type in executable

换回1.27.0就正常

**Comment by QQ4OU** [comment]
intel

**Comment by viarotel** [comment]
新的M系列处理器没有遇到该问题，如果还不行，你可能需要使用 homebrew 安装 scrcpy 后在偏好设置中自定义 scrcpy 路径

**Comment by QQ4OU** [comment]
您的方法可行

**Comment by QQ4OU** [comment]
路径：/usr/local/Cellar/scrcpy/3.0/bin/scrcpy

![路径](https://github.com/user-attachments/assets/f08c1d42-9803-44d7-b14d-d62d73527fe1)
![escrcpy](https://github.com/user-attachments/assets/f00d63cf-ab83-48cc-a25d-0e648b78ba29)
