### ISSUE TITLE
[Bug] 在连接一段时间后，在屏幕下半部分会出现一个圆圈的变形，重新连接后恢复，过段时间会再发生

### ISSUE THREAD

**Issue by wuerbuzuo** [viarotel-org/escrcpy#312]
使用的是wifi连接，机型是OPPO Find X8 Pro
![PixPin_2024-11-26_20-02-20](https://github.com/user-attachments/assets/d379b69b-6040-4f8c-a40a-f8d120867a9a)

**Comment by viarotel** [comment]
控制窗口完全由 scrcpy 提供支持，你需要向 scrcpy 反馈问题
