### ISSUE TITLE
小米11，安卓12版本

### ISSUE THREAD

**Issue by xiamo008** [viarotel-org/escrcpy#318]
你好大佬，我在使用电脑控制手机时候，复制出现一个问题，就是电脑复制的内容，能在手机里面识别到，但是每次不能直接复制，而是需要调用输入法之后，才可以复制，而且还必须要要提示运行权限才可以把内容复制到手机

而手机里面复制的内容 ，也无法直接到电脑上粘贴

我用的iqoo10p 手机，就能正常的双向的复制粘贴操作，求教下 我该如何改正这个问题呀，

2部手机都安装了，搜狗输入法，版本一样的

**Comment by viarotel** [comment]
那有可能是个别机型问题, 国内厂商总是对安卓系统进行一些定制和魔改导致的

**Comment by xiamo008** [comment]
> 那有可能是个别机型问题, 国内厂商总是对安卓系统进行一些定制和魔改导致的

这个有办法处理吗，我小米11 已经root了

**Comment by viarotel** [comment]
你可以将该问题报告给 [scrcpy](https://github.com/Genymobile/scrcpy)
