### ISSUE TITLE
[Bug] 在Android 15设备上，启用“控制时关闭屏幕”后，屏幕画面会被冻结

### ISSUE THREAD

**Issue by JackCui001** [viarotel-org/escrcpy#320]
研究了一下，发现很有可能是 Scrcpy v3.0 引入的新 bug。
隔壁也有 issue 在讨论，Genymobile/scrcpy#5530
在 Android 15 设备上必复现，在Android 14设备上则不会发生。

临时解决方案（2选1）：
1：回退到 Escrcpy 1.27.0（Scrcpy server v2.7）。
2：下载 issue 中作者提供的最新 scrcpy-server，替换到 Escrcpy\resources\extra\win\scrcpy 目录下。

希望等 Scrcpy v3.0.1 发布时，Escrcpy作者能早日合并，谢谢！

**Comment by ymbzd** [comment]
果然踩到了这个坑   请及时修复
