### ISSUE TITLE
[Help] 有没有办法调整关闭按钮的策略

### ISSUE THREAD

**Issue by Vixb1122** [viarotel-org/escrcpy#321]
之前关闭按钮选的最小化，目前想改成关闭按钮直接退出，没办法改

**Comment by viarotel** [comment]
进入 偏好设置页面 点击编辑 在配置文件中 将 "appCloseCode": xxx 这一列删掉 然后保存文件

**Comment by Vixb1122** [comment]
thx @viarotel
