### ISSUE TITLE
[Help] 希望可以添加一个置顶功能

### ISSUE THREAD

**Issue by HafenYin** [viarotel-org/escrcpy#322]
#### 需求
方便在使用浏览器+escrcpy等多窗口环境不需要经常切换，可以直接把escrcpy直接固定在最高层

#### 项目场景
比如说浏览器需要输入文本，但是OCR需要焦点在escrcpy上。这导致在浏览器输入的时候经常需要再次使用tab+alt切换回escrcpy

![20241204_115546_887_copy](https://github.com/user-attachments/assets/8b2ce9fc-f324-49bb-bcf8-df7a9b643d51)

**Comment by viarotel** [comment]
偏好设置的窗口控制中是有置顶选项的。

**Comment by HafenYin** [comment]
> 偏好设置的窗口控制中是有置顶选项的。

谢谢佬，刚上手没看到
