### ISSUE TITLE
安卓13  miui14.0.8  无法点击

### ISSUE THREAD

**Issue by bzsc2058** [viarotel-org/escrcpy#324]
#### Describe the bug
安卓版本13  miui14.0.8  无法点击,键盘输入,使用过1.22.4和1.27.5都不能,不知道那个版本能用吗?

**Comment by viarotel** [comment]
https://github.com/viarotel-org/escrcpy/blob/dev/README-CN.md#%E6%9F%90%E4%BA%9B%E8%AE%BE%E5%A4%87%E8%BF%9E%E6%8E%A5%E9%95%9C%E5%83%8F%E5%90%8E%E5%8F%AF%E4%BB%A5%E7%9C%8B%E5%88%B0%E7%94%BB%E9%9D%A2%E4%BD%86%E6%98%AF%E6%97%A0%E6%B3%95%E6%93%8D%E4%BD%9C
