### ISSUE TITLE
[Bug] 当使用单App投屏时，输入法无法正常显示

### ISSUE THREAD

**Issue by fatinghenji** [viarotel-org/escrcpy#325]
#### 当使用单App投屏时，输入法无法正常显示
当使用单App投屏时，输入法无法显示，只能盲打。如果这时通过`开始镜像`打开一个投屏，那么输入法的界面会出现在新的投屏上，而非当前输入的app，如下图所示。
![图片](https://github.com/user-attachments/assets/f4bc53e0-fe4b-4586-ad4f-51d41827372f)
我简单搜索了下issue里面似乎没人提到这个问题，所以打开了一个issue。
这是由于Android的特性导致的吗？还是说有什么解决办法？

**Comment by viarotel** [comment]
我不知道，但问题并不能由Escrcpy解决
