### ISSUE TITLE
[Help] 如何设置escrcpy关闭时缩小至系统托盘

### ISSUE THREAD

**Issue by long-dada** [viarotel-org/escrcpy#330]
第一次打开escrcpy关闭时弹出关闭选项，之后再打开escrcpy关闭没有弹窗了，我在escrcpy中没有找到如何更改escrcpy的设置，只有关于投屏的设置。

**Comment by viarotel** [comment]
我会在下个版本优化，临时解决方法 https://github.com/viarotel-org/escrcpy/issues/321

**Comment by long-dada** [comment]
感谢

**Comment by viarotel** [comment]
v1.28.0+ 以在偏好设置中添加控制主面板行为的选项
