### ISSUE TITLE
[FR] Wireless connection to already paired device

### ISSUE THREAD

**Issue by TheLastFlame** [viarotel-org/escrcpy#331]
I am now connecting my device to wireless adb using the [ADB QR ](https://marketplace.visualstudio.com/items?itemName=AakashP.adb-qr) extension for VSCode.

It automatically connects to the device with wifi debugging enabled.

I think such functionality should be in escrcpy, as it would make the user experience very easy by avoiding constant ip address entry.

**Comment by viarotel** [comment]
Good idea

**Comment by viarotel** [comment]
v1.28.0+ Supported

**Comment by TheLastFlame** [comment]
Not quite. The appearance of QR connection is already a good step forward, but I'm talking about another, more advanced feature of this extension. “Connect With Paired Device” automatically connects a device with wifi debugging enabled to the computer if it has already connected to it at least once. No QR scanning or ip entry. Probably a simple scan of devices on the local network with an attempt to connect to each one.
