### ISSUE TITLE
[Help] “启动相机”功能应该怎么翻转摄像头？

### ISSUE THREAD

**Issue by duolax** [viarotel-org/escrcpy#332]
![image](https://github.com/user-attachments/assets/75825285-dee8-49f2-9af9-fed4a991d38b)
求助，“启动相机后，该怎么翻转至前置摄像头？”

**Comment by viarotel** [comment]
偏好设置里面找找吧

**Comment by duolax** [comment]
> 偏好设置里面找找吧

感谢，找到了
![image](https://github.com/user-attachments/assets/1a521b71-4f66-46a7-8b40-ff0d1097cb05)
