### ISSUE TITLE
[Bug] 禁用视频转发闪退

### ISSUE THREAD

**Issue by Xiaoxi1185** [viarotel-org/escrcpy#333]
1.27.6, 1.27.7 win x64版本禁用视频转发scrcpy.exe闪退无法正常工作，1.27.5版本正常
图为1.27.5，1.27.6/1.27.7版本闪退
![屏幕截图 2024-12-13 112805](https://github.com/user-attachments/assets/8eb9aaab-ca48-423b-85b6-f11f2f8f2e8b)

**Comment by viarotel** [comment]
v1.28.0+ 已修复该问题
