### ISSUE TITLE
Please add av1 decoding support

### ISSUE THREAD

**Issue by aoy2024** [viarotel-org/escrcpy#337]
Please add av1 decoding support

**Comment by TheLastFlame** [comment]
Already available in the latest version

**Comment by aoy2024** [comment]
> Already available in the latest version已在最新版本中提供

不好意思我没找到选项
![11](https://github.com/user-attachments/assets/0e72e78c-f215-483d-a10f-5f3fd18b78c3)
![22](https://github.com/user-attachments/assets/6553e7a2-32bd-48fd-bc52-36bf04a9c495)

**Comment by TheLastFlame** [comment]
> > Already available in the latest version已在最新版本中提供
> 
> 不好意思我没找到选项 ![11](https://private-user-images.githubusercontent.com/166855936/396333102-0e72e78c-f215-483d-a10f-5f3fd18b78c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NDI4ODUsIm5iZiI6MTczNDQ0MjU4NSwicGF0aCI6Ii8xNjY4NTU5MzYvMzk2MzMzMTAyLTBlNzJlNzhjLWYyMTUtNDgzZC1hMTBmLTVmM2ZkMThiNzhjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxN1QxMzM2MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZTIyMDM0MWQ1MzhlYmIyNzliNjJhMzVlMDE3MjQ1YWNjNTE5ZDBlNmFkMGM3ZWRjNjA3MjRjYWM0NWZjODQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1fx1jEuBLuCGNVjuH9UDRLyZxI6ipdnqGzoyGOC3QqU) ![22](https://private-user-images.githubusercontent.com/166855936/396333115-6553e7a2-32bd-48fd-bc52-36bf04a9c495.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NDI4ODUsIm5iZiI6MTczNDQ0MjU4NSwicGF0aCI6Ii8xNjY4NTU5MzYvMzk2MzMzMTE1LTY1NTNlN2EyLTMyYmQtNDhmZC1iYzUyLTM2YmYwNGE5YzQ5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxN1QxMzM2MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NTZlMWI0MWJlZmM1YzJjYjBlODgwZDZlNDk1OTllN2I0NjUxOGI5YmMxODE5ZmY4YTlhN2U0MTExMTg4YWFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.g7abJm8dO_Qco7L19_VvcTbXGBOnO6hR82djqKospU0)

So av1 is not supported by your Android device

**Comment by aoy2024** [comment]
> > > Already available in the latest version已在最新版本中提供
> > 
> > 
> > 不好意思我没找到选项 ![11](https://private-user-images.githubusercontent.com/166855936/396333102-0e72e78c-f215-483d-a10f-5f3fd18b78c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NDI4ODUsIm5iZiI6MTczNDQ0MjU4NSwicGF0aCI6Ii8xNjY4NTU5MzYvMzk2MzMzMTAyLTBlNzJlNzhjLWYyMTUtNDgzZC1hMTBmLTVmM2ZkMThiNzhjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxN1QxMzM2MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZTIyMDM0MWQ1MzhlYmIyNzliNjJhMzVlMDE3MjQ1YWNjNTE5ZDBlNmFkMGM3ZWRjNjA3MjRjYWM0NWZjODQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1fx1jEuBLuCGNVjuH9UDRLyZxI6ipdnqGzoyGOC3QqU) ![22](https://private-user-images.githubusercontent.com/166855936/396333115-6553e7a2-32bd-48fd-bc52-36bf04a9c495.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NDI4ODUsIm5iZiI6MTczNDQ0MjU4NSwicGF0aCI6Ii8xNjY4NTU5MzYvMzk2MzMzMTE1LTY1NTNlN2EyLTMyYmQtNDhmZC1iYzUyLTM2YmYwNGE5YzQ5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxN1QxMzM2MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NTZlMWI0MWJlZmM1YzJjYjBlODgwZDZlNDk1OTllN2I0NjUxOGI5YmMxODE5ZmY4YTlhN2U0MTExMTg4YWFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.g7abJm8dO_Qco7L19_VvcTbXGBOnO6hR82djqKospU0)
> 
> So av1 is not supported by your Android device因此，您的 Android 设备不支持 av1

Big brother, I can use scrcpy -- video codec=av1 to project the screen normally. Are you sure

**Comment by YumeMichi** [comment]
oneplus 12 and xiaomi pad 6
![Uploading WX20241218-033539@2x.png…]()

**Comment by YumeMichi** [comment]
recorded file
```
scrcpy --video-codec=av1 --record=1.mp4
```
![WX20241218-033855@2x](https://github.com/user-attachments/assets/00a066d8-3c3d-47f1-8a20-c0d740930fdf)

**Comment by aoy2024** [comment]
找到问题了,原因是我链接了两台手机,另外一台手机不支持av1,单独设置支持的手机就有选项了 谢谢解答
![333](https://github.com/user-attachments/assets/bdac5b60-7328-460f-a38b-c78910ad8cad)
