### ISSUE TITLE
应用重新打开后只会自动重连部分设备

### ISSUE THREAD

**Issue by VegetableChicken0** [viarotel-org/escrcpy#344]
初始只有四台设备
![image](https://github.com/user-attachments/assets/61499925-1d09-4542-bb7a-0797b4c8c407)
偏好设置中也只显示了四台设备
![image](https://github.com/user-attachments/assets/824b8c31-f87d-4395-9a16-c1938dff645d)
关闭应用后又重新打开

![image](https://github.com/user-attachments/assets/2ebe26ea-2a94-46c3-a826-5c7d8f3b701c)
![image](https://github.com/user-attachments/assets/e1b951e2-64ab-4d5c-aec2-4cf7b2093043)
又多了一台设备

设备连接都是通过usb连接后，点击无线模式
每次自动重连只会显示1、2、3号，4、5号都需要手动连接
感谢作者大大看看，是不是我哪步操作有问题

**Comment by VegetableChicken0** [comment]
版本是v1.27.7

**Comment by VegetableChicken0** [comment]
![image](https://github.com/user-attachments/assets/a3ad2fbb-dd7b-44a7-92be-d31e78e312d7)
显示三个失败，请问哪里可以看到日志及错误消息
![image](https://github.com/user-attachments/assets/ba88595d-61c3-4c73-9741-68b26fa50221)
这运行日志好像没有体现

**Comment by VegetableChicken0** [comment]
![image](https://github.com/user-attachments/assets/4181e7d7-ac34-4bb5-ad76-12510f1eda52)
是否是此处的问题，历史保存的端口不是5555导致的无法自动重连？

**Comment by VegetableChicken0** [comment]
请问历史连接里边的端口号信息在哪里可以修改呢

**Comment by viarotel** [comment]
试试 v1.28.1+版本吧

**Comment by VegetableChicken0** [comment]
感谢回复，问题已解决。
配置时1、2、3号设备都是通过usb连接后开启无限模式，连接历史中的端口就是5555
配置4、5设备时，使用的是无线配置的方式，端口当时配置的是手机中的配对端口；
刚在下拉框中把端口不正确的设备删除后重新连接，现在能正常自动重连了
