### ISSUE TITLE
使用二维码连接,没法成功扫码

### ISSUE THREAD

**Issue by aoy2024** [viarotel-org/escrcpy#345]
没法成功扫码配对 哪怕我把屏幕上的二维码放大 手机也没法识别配对使用的是1.28.1版本
![wechat_2024-12-20_144359_854](https://github.com/user-attachments/assets/228a73d8-5c56-461c-80c4-0f96b6b244e6)

**Comment by aoy2024** [comment]
另外根据新版本字体有点小 能否提供字体大小修改选项 谢谢

**Comment by viarotel** [comment]
在开发者模式中打开并进入无线调试
点击使用二维码配对设备

**Comment by viarotel** [comment]
字体小试试把窗口拖大点...

**Comment by aoy2024** [comment]
> 在开发者模式中打开并进入无线调试 点击使用二维码配对设备

是的 在无线调试界面扫码 我这的情况是手机一直扫不上码
![2](https://github.com/user-attachments/assets/f440dfcf-d5e6-4258-b2ff-cc6007c81c6b)

**Comment by aoy2024** [comment]
> 字体小试试把窗口拖大点...

好的谢谢

**Comment by aoy2024** [comment]
> > 字体小试试把窗口拖大点...
> 
> 好的谢谢

这个设置很巧妙 嘿嘿

**Comment by viarotel** [comment]
那就不知道了，我的几个手机都可以，请确保手机和PC的网是位于一个频段

**Comment by aoy2024** [comment]
> 那就不知道了，我的几个手机都可以，请确保手机和PC的网是位于一个频段
我使用的是投影仪当显示器 可能是清晰度问题 虽然我已经把二维码图片放大到很大了 测试了两台手机都没有反应 用微信扫码倒是能识别到

**Comment by aoy2024** [comment]
> 那就不知道了，我的几个手机都可以，请确保手机和PC的网是位于一个频段

我使用的是投影仪当显示器 可能是清晰度问题 虽然我已经把二维码图片放大到很大了 测试了两台手机都没有反应 用微信扫码倒是能识别到

**Comment by aoy2024** [comment]
如果可以 请把使用配对码配对功能加上

**Comment by viarotel** [comment]
> 如果可以 请把使用配对码配对功能加上

当你直接使用IP和端口号连接失败超时后会自动触发展示输入配对码连接的窗口

**Comment by aoy2024** [comment]
> > 如果可以 请把使用配对码配对功能加上
> 
> 当你直接使用IP和端口号连接失败超时后会自动触发展示输入配对码连接的窗口

明白 谢谢
