### ISSUE TITLE
Bug反馈与建议

### ISSUE THREAD

**Issue by zxp19821005** [viarotel-org/escrcpy#37]
如题。
我已经将该程序移植到了ArchLinux的AUR：[escrcpy](https://aur.archlinux.org/packages/escrcpy)
目前编译后可以运行，但终端有报错：
日志如下：
```
$ ./src/escrcpy-1.7.1/dist-release/linux-unpacked/escrcpy 
[384798:1020/151349.887468:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: 无此接口“org.freedesktop.portal.FileChooser”
[384798:1020/151349.887512:ERROR:select_file_dialog_linux_portal.cc(274)] Failed to read portal version property
[384798:1020/151349.923041:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.UnknownMethod: 在路径 org.freedesktop.portal.Settings 的对象上没有“/org/freedesktop/portal/desktop”接口
```

在[v1.6.10](https://github.com/viarotel-org/escrcpy/releases/tag/v1.6.10)版本的时候，软件界面无报错，运行5~8秒左右白屏；
在[v1.7.1](https://github.com/viarotel-org/escrcpy/releases/tag/v1.7.1)版本的时候，软件启动时界面就会有报错：
```
spawn /home/zxp-endeavouros/.cache/paru/clone/escrcpy/src/escrcpy-1.7.1/dist-release/linux-unpacked/resources/extra/core/adb.exe EACCES
```
终端下报错信息和1.6.10的信息一样。
运行编译好的AppImage文件，运行5~8秒左右白屏；报错信息如下：
```
spawn /tmp/.mount_EscrcppEk1wA/resources/extra/core/adb.exe EACCES
```
能不能打包的时候做个判断，如果是Linux的话，就不要将[extra/core](https://github.com/viarotel-org/escrcpy/tree/main/electron/resources/extra/core)打包进去？

**Comment by viarotel** [comment]
@viarotel 我目前的工作流没有Linux环境，这也是为什么我没有发布Linux以及MacOS软件包的原因，因为没有方法进行测试，不过我近期做的一些改动就为了兼容Linux以及MacOS平台，上述的问题我会在近期解决，当然如果你想要更快解决的话，请尝试克隆该代码库贡献一些代码

**Comment by viarotel** [comment]
@zxp19821005 好消息，似乎并没有做多少修改，我稍加改动后成功编译出了Linux以及MacOS软件包，欢迎试用

**Comment by viarotel** [comment]
> ![image](https://github.com/viarotel-org/escrcpy/assets/29135984/e9b80653-9b24-4b95-bc60-fd01b276c6d8)
> 
> 下载不下来
> 
> 

咋还报毒了，搞笑，晚点我测试一下

**Comment by viarotel** [comment]
> ![image](https://github.com/viarotel-org/escrcpy/assets/29135984/e9b80653-9b24-4b95-bc60-fd01b276c6d8)
> 
> 下载不下来
> 
> 什么浏览器

**Comment by Jonnyan404** [comment]
1.8.13也报毒了

**Comment by viarotel** [comment]
> 1.8.13也报毒了

什么浏览器

**Comment by viarotel** [comment]
> 1.8.13也报毒了

我用谷歌浏览器没事

**Comment by Jonnyan404** [comment]
> > 1.8.13也报毒了
> 
> 我用谷歌浏览器没事

就是Google浏览器，这是window10系统的 window defender 拦截的

**Comment by viarotel** [comment]
> > > 1.8.13也报毒了
> 
> > 
> 
> > 我用谷歌浏览器没事
> 
> 
> 
> 就是Google浏览器，这是window10系统的 window defender 拦截的

关了这个玩意，没啥用，总是异常爆毒，应该是应用没有签名，所以它认为是有害软件，开源的东西里面用了啥，一清二楚。

**Comment by viarotel** [comment]
已将解决方法添加到 [常见问题](https://github.com/viarotel-org/escrcpy#%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6%E5%8C%85%E6%97%B6%E6%8F%90%E7%A4%BA%E6%8A%A5%E6%AF%92%E5%AF%BC%E8%87%B4%E6%97%A0%E6%B3%95%E6%AD%A3%E5%B8%B8%E4%B8%8B%E8%BD%BD) 请参阅并尝试该解决方法
