### ISSUE TITLE
关于添加悬浮按钮菜单的问题

### ISSUE THREAD

**Issue by zhoujia456888** [viarotel-org/escrcpy#56]
对于我这种记不住快捷键的人来说，吸附悬浮菜单按钮还是挺有用的。
不知道楼主有没有对应的方案，没有的话就算了。
另外我在Mac上点退出选择最小化到dock的时候，没办法再让程序显示了。只能退出再重新打开。
![image](https://github.com/viarotel-org/escrcpy/assets/7905253/b64cf710-06cd-4a27-bc84-af0d8423f27b)
![image](https://github.com/viarotel-org/escrcpy/assets/7905253/bf54d186-a17c-408f-8e34-b372c0d04719)

**Comment by viarotel** [comment]
@zhoujia456888 最小化到托盘以后顶部右侧的状态栏有图标吗?

**Comment by viarotel** [comment]
吸附悬浮菜单这个说明过了，关键吃力不讨好，还有可能引发性能问题，所以暂时不会加入

**Comment by zhoujia456888** [comment]
没有图标

![image](https://github.com/viarotel-org/escrcpy/assets/7905253/520d74ec-5326-4a22-b52e-c43e08d82373)

**Comment by viarotel** [comment]
好的感谢反馈 我尽快解决这个问题

**Comment by viarotel** [comment]
@zhoujia456888 v1.9.1 已解决 macOS 窗口控制问题 请更新
