### ISSUE TITLE
无法通过escrcpy直接启用投屏（镜像）和录制功能

### ISSUE THREAD

**Issue by xiaoyangdkj** [viarotel-org/escrcpy#58]
应用版本：V1.9.0
运行环境：Windows 11 x64
触发操作：通过无线连接手机5555端口后，会显示连接成功但无法“开始镜像”
![屏幕截图 2023-10-24 165337_edit_1392308226118797](https://github.com/viarotel-org/escrcpy/assets/82305021/3a7925bc-5361-4429-aa74-1b1bbc5877c4)

临时解决方法：在escrcpy无线连接后，最小化窗口并直接打开 \core\scrcpy.exe 里的本体进行“开始镜像”
<img width="1280" alt="屏幕截图 2023-10-24 170142" src="https://github.com/viarotel-org/escrcpy/assets/82305021/497f4b63-8aaa-4c9b-9598-7417a057a46e">

**Comment by viarotel** [comment]
@xiaoyangdkj [解决方法](https://github.com/viarotel-org/escrcpy#%E8%8E%B7%E5%8F%96%E8%AE%BE%E5%A4%87%E5%88%97%E8%A1%A8%E5%A4%B1%E8%B4%A5%E6%88%96%E5%BC%80%E5%A7%8B%E9%95%9C%E5%83%8F%E5%BD%95%E5%B1%8F%E6%8A%A5%E9%94%99)
请下载最新的 v1.9.1 彻底解决这个问题

**Comment by viarotel** [comment]
这个是配置依赖缓存问题 重置一下配置

**Comment by xiaoyangdkj** [comment]
> @xiaoyangdkj [解决方法](https://github.com/viarotel-org/escrcpy#%E8%8E%B7%E5%8F%96%E8%AE%BE%E5%A4%87%E5%88%97%E8%A1%A8%E5%A4%B1%E8%B4%A5%E6%88%96%E5%BC%80%E5%A7%8B%E9%95%9C%E5%83%8F%E5%BD%95%E5%B1%8F%E6%8A%A5%E9%94%99) 请下载最新的 v1.9.1 彻底解决这个问题

问题还是无法解决，在重置配置后依然返回“Command failed with code 1”
这个问题不是在更新escrcpy后出现的，而是在第一次安装escrcpy时出现的
在更换adb配置路径和使用“以管理员身份运行”后还是如此

**Comment by viarotel** [comment]
按下 Ctrl + Shift + I 进入开发者工具，并查看是否有任何报错信息。

**Comment by viarotel** [comment]
偏好设置右上方编辑配置打开截个图

**Comment by S-H-Go** [comment]
# 配置
{
	"scrcpy": {
		"global": {
			"--no-audio": false,
			"savePath": "C:\\Users\\wangs\\OneDrive\\桌面",
			"--show-touches": false,
			"--stay-awake": false,
			"--turn-screen-off": false,
			"--power-off-on-close": false,
			"--no-power-on": false,
			"--record-format": "mp4",
			"--max-size": "",
			"--video-bit-rate": "",
			"--max-fps": "",
			"--video-codec": "",
			"--video-encoder": "",
			"--rotation": "",
			"--crop": "",
			"--display": "",
			"--display-buffer": "",
			"--audio-buffer": "",
			"--v4l2-buffer": "",
			"--no-video": false,
			"--window-borderless": false,
			"--fullscreen": false,
			"--always-on-top": false,
			"--disable-screensaver": false,
			"scrcpyPath": ""
		},
		"scope": "global",
		"mix3_phone_5555": {
			"--no-audio": false,
			"savePath": "C:\\Users\\wangs\\OneDrive\\桌面",
			"--show-touches": false,
			"--stay-awake": false,
			"--turn-screen-off": false,
			"--power-off-on-close": false,
			"--no-power-on": false,
			"--record-format": "mp4",
			"--max-size": "",
			"--video-bit-rate": "",
			"--max-fps": "",
			"--video-codec": "",
			"--video-encoder": "",
			"--rotation": "",
			"--crop": "",
			"--display": "",
			"--display-buffer": "",
			"--audio-buffer": "",
			"--v4l2-buffer": "",
			"--no-video": false,
			"--window-borderless": false,
			"--fullscreen": false,
			"--always-on-top": false,
			"--disable-screensaver": false
		}
	}
}

# 控制台报错
![image](https://github.com/viarotel-org/escrcpy/assets/73683678/f7329014-a1a3-4ade-9482-403741ddf44b)

**Comment by viarotel** [comment]
这个已经找到原因了 安装路径不能有空格 下个版本解决 
暂时解决方法 "不要安装到有空格的目录解决"

**Comment by xiaoyangdkj** [comment]
> 偏好设置右上方编辑配置打开截个图
具体是？
<img width="1280" alt="屏幕截图 2023-10-26 090709" src="https://github.com/viarotel-org/escrcpy/assets/82305021/3beeb845-3aaa-4204-ab35-ef72c0a12507">

**Comment by xiaoyangdkj** [comment]
> 这个已经找到原因了 安装路径不能有空格 下个版本解决 暂时解决方法 "不要安装到有空格的目录解决"

感谢你的建议，目前已通过更换安装目录的方式解决
<img width="1280" alt="屏幕截图 2023-10-26 091205" src="https://github.com/viarotel-org/escrcpy/assets/82305021/38f748f6-2acc-43c6-bd88-236141499353">

**Comment by viarotel** [comment]
[v1.10.1](https://github.com/viarotel-org/escrcpy/releases/tag/v1.10.1) 以上已修复该问题
