### ISSUE TITLE
第一次下载使用本软件, 没有成功连接上过

### ISSUE THREAD

**Issue by DBinK** [viarotel-org/escrcpy#60]
应用版本：V1.9.1
运行环境：Windows 11 x64
触发操作：无论是点开始镜像或无线模式的连接设备都无法连接
![image](https://github.com/viarotel-org/escrcpy/assets/21201676/22362e3a-d4ac-4f2c-b206-0ea0a962da80)

我是第一次下载使用本软件, 没有成功连接上过

释放在安装目录 D:\Program Files\Escrcpy\resources\extra\core\ 的 scrcpy.exe 双击是能正常运行的

**Comment by viarotel** [comment]
打开开发者工具看看报错

**Comment by DBinK** [comment]
![image](https://github.com/viarotel-org/escrcpy/assets/21201676/7512bafc-84f8-4ddb-b6bb-ea4749582fac)
VM160 D:\Program Files\Escrcpy\resources\app.asar\dist-electron\preload.js

**Comment by DBinK** [comment]
> ![image](https://user-images.githubusercontent.com/21201676/277854676-7512bafc-84f8-4ddb-b6bb-ea4749582fac.png) VM160 D:\Program Files\Escrcpy\resources\app.asar\dist-electron\preload.js

**Comment by DBinK** [comment]
> 打开开发者工具看看报错

![image](https://github.com/viarotel-org/escrcpy/assets/21201676/7a22b0f4-ea66-4675-bf86-f479bb884389)

日志全文:
```
VM160 D:\Program Files\Escrcpy\resources\app.asar\dist-electron\preload.js:228 client z5bin: "D:\\Program Files\\Escrcpy\\resources\\extra\\core\\adb.exe"host: "127.0.0.1"options: {host: '127.0.0.1', port: 5037, bin: 'D:\\Program Files\\Escrcpy\\resources\\extra\\core\\adb.exe', timeout: 0}port: 5037timeout: 0_events: {}_eventsCount: 0_maxListeners: undefinedSymbol(kCapture): false[[Prototype]]: EventEmitter
index-661a613b.js:86 electron Objectconfigs: {adbPath: 'D:\\Program Files\\Escrcpy\\resources\\extra\\core\\adb.exe', desktopPath: 'D:\\Desktop', devPublishPath: 'D:\\Program Files\\Escrcpy\\dev-publish.yml', icnsLogoPath: 'D:\\Program Files\\Escrcpy\\electron\\resources\\build\\logo.icns', icoLogoPath: 'D:\\Program Files\\Escrcpy\\electron\\resources\\build\\logo.ico', …}ipcRenderer: {send: ƒ, sendTo: ƒ, sendSync: ƒ, sendToHost: ƒ, postMessage: ƒ, …}process: {platform: 'win32', versions: {…}, env: {…}}webFrame: {insertCSS: ƒ, setZoomFactor: ƒ, setZoomLevel: ƒ}[[Prototype]]: Object
index-661a613b.js:28 getDeviceData.data Proxy(Array)[[Handler]]: zm[[Target]]: Array(1)[[IsRevoked]]: false
VM160 D:\Program Files\Escrcpy\resources\app.asar\dist-electron\preload.js:228 scrcpyProcess.stderr.data: 'D:\Program' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

（匿名） @ VM160 D:\Program Files\Escrcpy\resources\app.asar\dist-electron\preload.js:228
emit @ VM24 node:events:514
addChunk @ VM57 readable:324
readableAddChunk @ VM57 readable:297
（匿名） @ VM57 readable:234
onStreamRead @ VM82 stream_base_commons:190

```

**Comment by DBinK** [comment]
看起来好像是安装路径不能有空格, 但我也只是安装到常规的 Windows 软件安装目录 `Program Files` , 这个应该要修一下

我尝试安装到别的目录之后, 可以正常使用了

**Comment by DBinK** [comment]
![image](https://github.com/viarotel-org/escrcpy/assets/21201676/b8ca7c03-a18a-4bd2-910a-2d5732dfcdae)

希望这个数字可以改成自定义

应用场景: https://www.bilibili.com/video/av418639099

**Comment by viarotel** [comment]
确实是这样，我已经修复了，下个版本解决这些问题，多屏幕这个很好的建议，感谢反馈。就喜欢你这种动手能力强的用户，给你点个赞👍

**Comment by DBinK** [comment]
> 确实是这样，我已经修复了，下个版本解决这些问题，多屏幕这个很好的建议，感谢反馈。就喜欢你这种动手能力强的用户，给你点个赞👍

也很感谢你能开发这个功能丰富、界面美观的应用😚

之前好像有个叫 tomato 的好用的 gui 但是不更新了，在 GitHub 上试用了好几个项目，觉得你的这个最美观实用

**Comment by viarotel** [comment]
[v1.10.1](https://github.com/viarotel-org/escrcpy/releases/tag/v1.10.1) 以上已修复该问题
