### ISSUE TITLE
安卓14开启控制时关闭屏幕失效

### ISSUE THREAD

**Issue by ooil929** [viarotel-org/escrcpy#74]
已开启“控制时关闭屏幕”，但没有效果，控制时还是亮着屏幕，反而是结束控制时关闭屏幕有效
![image](https://github.com/viarotel-org/escrcpy/assets/39184577/50d1a81e-aca7-40cd-a1a6-0d99863b08c6)

**Comment by Andrea-lyz** [comment]
试试alt+o？亮屏多个shift。另外这个问题不是Android14的问题，13也有

**Comment by viarotel** [comment]
我的一加5可以 有可能某些机型上安卓版本更高权限控制更严格，需要在开发者选项中开启更多的功能，具体是那个功能你的这边可以研究一些 如果解决了可以在这里提供一下解决方法，这个不是 Escrcpy 的问题

**Comment by viarotel** [comment]
v1.12.0 以上已修复该问题
