### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by Andrea-lyz** [viarotel-org/escrcpy#75]
1，加入adb功能，实现例如连接[自动切换输入法](https://github.com/Genymobile/scrcpy/issues/1055#issuecomment-1544981820)的功能
2，对于某些黑厂机器（比如一加11），会出现全程音频杂音，scrcpy那边给了[解决方案](https://github.com/Genymobile/scrcpy/issues/3793#issuecomment-1465204571)，但似乎没有添加开关，只能手动修改配置文件添加"--audio-output-buffer": "10",，感觉可以做个适配，自行添加一些奇奇怪怪的启动命令
3，能不能做个对于镜像窗口的悬浮条，来控制返回主页多任务以及及时的开关屏幕（alt+o），录制，等操作
4，保存历史IP地址，启动后一键连接

**Comment by viarotel** [comment]
非常好的建议，等我有空闲时间的话，尝试实现上述中的一些功能

**Comment by pikakolendo02** [comment]
![图片](https://github.com/viarotel-org/escrcpy/assets/15796641/e9885e49-ff31-490a-afc3-0df10142f64a)
一个小建议，关闭electron的拼写检查

**Comment by pikakolendo02** [comment]
建议增加音频编码/码率选项
https://github.com/Genymobile/scrcpy/blob/master/doc/audio.md#codec

**Comment by viarotel** [comment]
目前已实现以下功能：
1. 无线历史连接，现在你可以选择连接过的无线设备，并且将保存到配置文件中，你也可以直接通过配置文件添加或移除历史连接，非常方便迁移和导入。
2. 已加入更多 Scrcpy 选项，包括并不限于 音频编码/码率选项/音频缓冲
3. 已默认关闭拼写检查
注意：需要 v1.12.1 及以上版本

即将加入的功能：
1. 支持附加自定义命令

优先级较低的功能（以后有可能加入）
1. 连接后自动切换输入法

暂无计划的功能：
1. 对于镜像窗口的悬浮条，请参阅 [操作栏说明](https://github.com/viarotel-org/escrcpy/blob/main/README-CN.md#%E8%AE%BE%E5%A4%87%E4%BA%A4%E4%BA%92%E6%8E%A7%E5%88%B6%E6%A0%8F%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%8D%E8%AE%BE%E8%AE%A1%E4%B8%BA%E8%87%AA%E5%8A%A8%E8%B7%9F%E8%B8%AA%E5%90%B8%E9%99%84%E7%9A%84%E6%82%AC%E6%B5%AE%E8%8F%9C%E5%8D%95)

**Comment by Andrea-lyz** [comment]
> 目前已实现以下功能：
> 
> 1. 无线历史连接，现在你可以选择连接过的无线设备，并且将保存到配置文件中，你也可以直接通过配置文件添加或移除历史连接，非常方便迁移和导入。
> 2. 已加入更多 Scrcpy 选项，包括并不限于 音频编码/码率选项/音频缓冲
> 3. 已默认关闭拼写检查
> 
> 注意：以上功能需要 v1.12.1 及以上版本
> 
> 即将加入的功能：
> 
> 1. 支持附加自定义命令
> 
> 优先级较低的功能（以后有可能加入）
> 
> 1. 连接后自动切换输入法
> 
> 暂无计划的功能：
> 
> 1. 对于镜像窗口的悬浮条，请参阅 [操作栏说明](https://github.com/viarotel-org/escrcpy/blob/main/README-CN.md#%E8%AE%BE%E5%A4%87%E4%BA%A4%E4%BA%92%E6%8E%A7%E5%88%B6%E6%A0%8F%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%8D%E8%AE%BE%E8%AE%A1%E4%B8%BA%E8%87%AA%E5%8A%A8%E8%B7%9F%E8%B8%AA%E5%90%B8%E9%99%84%E7%9A%84%E6%82%AC%E6%B5%AE%E8%8F%9C%E5%8D%95)

非常感谢！
另外还有点小建议：
1能否实现scrcpy窗口的吸顶隐藏或者贴边隐藏？
2然后我有个大胆的想法....因为我发现我一直用的剪切板同步 通知流转 文件传送的软件Fnsyn删库跑路了，于是在寻找新的软件，然后我发现似乎并没有同类型的流转软件和scrcpy结合起来，于是有了以下想法：
就如普通流转工具一样，有一个Android端软件来接收剪切板，通知等内容，然后通过局域网和win端应用配对保持连接，如果给予这个app非root(shizuku等)或者Root权限，能够开关远程adb端口，将获取到的adb地址和端口发送到win端，然后自动连接，便不在手动输入了。（开关远程adb也能通过自己设置快捷方式(酷安，支持root和非root方式)，然后调用快捷设置通过的功能短链实现，这样就不用单独做功能模块了）
对于剪切板等功能，如果没有启动scrcpy，则通过上述Android端和win端保持局域网连接然后共享剪切板和实现一些scrcpy没有的功能。当连接scrcpy时，就暂停前文的局域网实现，因为scrcpy连接时本身就实现了类似功能，如剪切板同步。
这样就实现了Android通用的类跨屏互联。
当然，这是我突发奇想的哈哈见笑了
这是我找到的[流转软件](https://github.com/doraemonkeys/WindSend)，也许能合作一波

**Comment by viarotel** [comment]
@Andrea-lyz 非常喜欢你们这种有想法的用户，总是带给我源源不断的灵感，同时也让我掉了不少头发（手动狗头），我仔细评估了你的需求，觉得一部分是可行的比如单独开启共享剪切板服务，这个即将列入计划中。另外你推荐的流转软件也很不错，已 Star 后期如果该软件支持全平台我可能会加入进来（毕竟集成的话可以省不少事，同时少掉些头发哈哈）

**Comment by Andrea-lyz** [comment]
@viarotel 我还想起来，scrcpy可以实现多屏多应用操作（单一设备，多个scrcpy窗口，每个窗口单独操作一个APP），不知道能否在Escrcpy中实现呢？
效果参考[Uncon](https://www.coolapk.com/apk/com.nightmare.remote) 但是目前看起来他是弃坑了（doge），不过之前真的挺好用的

另外我看scrcpy话题里有个[多窗口脚本](https://www.coolapk.com/feed/50787175?shareKey=ODIyZDQ3NjMxNDc1NjU0ODUxYmI~&shareUid=675530&shareFrom=com.coolapk.market_13.3.5)，也@了你，希望加入，但你应该没看到（doge），不过他这个脚本在我设备有问题，我在评论里描述了😂

**Comment by uzcool** [comment]
现在局域网剪贴板 用的kde connect ,但是感觉来说还是蛮重的..同步一个剪贴板 要400多M的软件...希望早日能 直接电脑复制 手机粘贴和 直接电脑上打字输入到手机内容..
