### ISSUE TITLE
设备交互控制栏增加更多常用功能

### ISSUE THREAD

**Issue by chenbaker** [viarotel-org/escrcpy#82]
使用了很好用，能不能搞一个黑屏开屏开关。偏好设置只有一个”控制时关闭屏幕“，连接的时候手机黑了，但如果需要手机亮，只能按手机电源键，按了，电脑也黑了。象QtScrcpy、anlink一样，在设备列表功能栏里搞一个黑屏亮屏开关，谢谢！

**Comment by viarotel** [comment]
@chenbaker 有这个选项 控制时关闭屏幕 如果开启后不起作用有可能是你操作的是全局的配置，针对单个设备的配置里面是关闭的

**Comment by chenbaker** [comment]
@viarotel 能不能把快捷键，做成开关，都放到”设备交互控制栏“那里？比如”关屏“”亮屏“”旋转屏幕“等，真不想背快捷键的命令了

**Comment by viarotel** [comment]
@chenbaker 这个问题在常见问题中已经解释过了

**Comment by chenbaker** [comment]
@看了常见问题，是解释了不使用悬浮菜单和吸附功能的原因。我的意思不是做悬浮菜单和吸附。意思是把快捷键做成开关放在这里：加上“启用/关闭音频、”关屏/亮屏“、”旋转屏幕“等，不用背快捷键命令
![20231107152324](https://github.com/viarotel-org/escrcpy/assets/26577466/ebbc237a-6af0-443f-8e6a-4460de5fd9d5)

**Comment by viarotel** [comment]
@chenbaker 抱歉我理解错了，你说的这个会考虑加上，非常感谢你的建议。

**Comment by chenbaker** [comment]
@viarotel 已经到最新版1.13，设备交互栏只增加了一个“多屏协同”，不够。提一个建议，能不能加一个保留历史连接记录。因为我发现Escrcpy大机率”刷新设备“找不到设备，每次打开Ecrcpy，都要点一次连接设备，下面才显示相关设备。我使用多台手机，要输入多次IP地址，点多次”连接设备“，极麻烦。如果有一个连接历史记录，直接点历史记录的连接就很方便，没有必要重复输入IP，重复点”连接设备“。
![1](https://github.com/viarotel-org/escrcpy/assets/26577466/aacdbddf-52c8-4a20-be02-223fb2aeb56c)

**Comment by viarotel** [comment]
这位大哥，虽然你的某些建议很好，但是你的用词让我很不爽，啥叫只增加了一个多屏协同，还不够，其他的优化你是没发现吗？你可以对自行比一下上个版本，而且这个工具我开发出来首先是满足我自己用的，我还没有实现财富自由，我需要上班维持我的生活，所以我不可能那么快实现你想要的功能，你的措辞让我觉得是在被催促，大家想要的功能，如果确实很有用的话我会逐个进行实现，甚至如果各位朋友有开发能力的话，完全可以参与进来，开源项目光靠我一人是不够的。

**Comment by chenbaker** [comment]
@viarotel 对不起了，真的是无意的。可能是一些方言用了书面表达导致用词不当。真的抱歉。刚从外面搬砖回来。看到你的留言，我马上回了，再次说声对不起，以后我会注意这些问题。谢谢你开发出这么优秀的软件，辛苦了。

**Comment by chenbaker** [comment]
@viarotel 这个工具我也是才用几天，是我太心急了提建议。这位老弟，我再次说跟你说声对不起了。

**Comment by viarotel** [comment]
没事，说明白就行，我欢迎提建议但是要有起码的尊重，毕竟我也没收你一分钱不是

**Comment by viarotel** [comment]
v1.13.2 已加入 旋转屏幕 音量控制 以及 文件推送，设备黑屏问题请通过尝试右键点击设备控制窗口或者电源键按钮解决，至于下载设备文件功能我有更多想法后期会加入，欢迎试用，该话题已过时我将关闭它。

**Comment by ajmz** [comment]
请问开启多屏协同之后，如何关闭？

> v1.13.2 已加入 旋转屏幕 音量控制 以及 文件推送，设备黑屏问题请通过尝试右键点击设备控制窗口或者电源键按钮解决，至于设备连接历史记录，下载设备文件功能我有更多想法后期会加入，欢迎试用，该话题已过时我将关闭它。

**Comment by viarotel** [comment]
@ajmz 正常情况下 关闭所有多屏协同打开的控制窗口后会自动停止多屏协同 遇到什么问题吗？关闭所有控制窗口后手机上的叠加显示器没有自动清除吗？

**Comment by ajmz** [comment]
> @ajmz 正常情况下 关闭所有多屏协同打开的控制窗口后会自动停止多屏协同 遇到什么问题吗？关闭所有控制窗口后手机上的叠加显示器没有自动清除吗？

是的，关闭后还在。
这个叠加显示器进程的名称是什么？

**Comment by viarotel** [comment]
请尝试使用 “adb shell settings put global overlay_display_devices none” 执行一些这个命令

**Comment by ajmz** [comment]
> 请尝试使用 “adb shell settings put global overlay_display_devices none” 执行一些这个命令

谢谢，已经执行命令后关闭。

**Comment by viarotel** [comment]
@ajmz 你可以 开启debug 后重新尝试多屏协同 如果关掉之后还是无法自动关闭叠加显示器 可以给我提供一下日志 我查一下看看是那里的问题

**Comment by ajmz** [comment]
> @ajmz 你可以 开启debug 后重新尝试多屏协同 如果关掉之后还是无法自动关闭叠加显示器 可以给我提供一下日志 我查一下看看是哪里的问题

已发邮箱

**Comment by viarotel** [comment]
@ajmz 看日志你似乎启用多屏协同之后软件重载了？从而导致关闭无法调用到关闭叠加屏幕方法。

**Comment by ajmz** [comment]
> @ajmz 看日志你似乎启用多屏协同之后软件重载了？从而导致关闭无法调用到关闭叠加屏幕方法。

是手机端还是电脑端重载？

**Comment by ajmz** [comment]
> @ajmz 看日志你似乎启用多屏协同之后软件重载了？从而导致关闭无法调用到关闭叠加屏幕方法。

看到新版本的多屏协同，增加了“关闭辅助显示设备”，但只能断开连接后再重新连接，才能关闭，建议再改进一下。

**Comment by viarotel** [comment]
@ajmz 没明白你什么意思，多屏协同就是基于这个叠加窗口才能用，如果运行起来之后关闭了叠加窗口那么打开的多个控制窗口也将不能使用变成黑屏，所以运行中的时候我禁用的叠加窗口

**Comment by ajmz** [comment]
> @ajmz 没明白你什么意思，多屏协同就是基于这个叠加窗口才能用，如果运行起来之后关闭了叠加窗口那么打开的多个控制窗口也将不能使用变成黑屏，所以运行中的时候我禁用了叠加窗口
> 
> 难道是你开启多屏协同之后关闭所有窗口多屏协同依然在运行（loading依然在转）导致你无法关闭？

是的，开启多屏协同之后关闭所有窗口多屏协同依然在运行。但最新版本的修改可以不用断开重连，就能“关闭辅助显示设备”了。
