### ISSUE TITLE
添加群组

### ISSUE THREAD

**Issue by fanlushuai** [viarotel-org/escrcpy#84]
一 分组：

1. 设备连上后，记录这台设备的指纹
2. 在设备上，可进行分组管理。分组设计成，1台手机可以为，多个组。
3. 在某个分组里面，可批量进行操作。

二 操控：
除了一般的一次性操作。能不能支持脚本管理。可以填入，自己定义的脚本。并且可以自定义多个，作为任务。
而这些任务，都可以随便执行？

**Comment by viarotel** [comment]
”在设备上“进行分组管理？做一个APP?
还是说在 Escrcpy 中可以添加分组，单个设备可以存在与多个分组中？类似 TeamViewer 那样？

**Comment by viarotel** [comment]
不过可以在 Escrcpy 中添加分组确实是一个很好建议，已列入计划中，感谢你的建议。
