### ISSUE TITLE
保持清醒这个好像不管用

### ISSUE THREAD

**Issue by fanlushuai** [viarotel-org/escrcpy#85]
手机型号，oppok9

我直接用adb命令。保持清醒也不管用。svc power stayon usb

有没有其他办法？

**Comment by viarotel** [comment]
安卓机型太多，不可能所有都兼顾到，如果刚好支持的话，恭喜；不支持的话，抱歉。这个只是 Scrcpy 的 GUI 工具，可以 Scrcpy 提 Issue
