### ISSUE TITLE
Gnirehtet Functionality Enhancement

### ISSUE THREAD

**Issue by Unknown78** [viarotel-org/escrcpy#90]
This is a feature request.
Currently, this software could only start it, but not monitor or stop it.

It'll be nice to able to monitor the status and stop it if needed on each device.

**Comment by viarotel** [comment]
Hello, currently you can monitor it in the log by turning on the debug option. As for stopping it, I rarely use it so I just make it as simple as possible. Currently you can stop it manually on the device or when exiting the software. It will also stop automatically. I will take the time to optimize it later, thank you for your suggestions!

**Comment by Unknown78** [comment]
Hi, thanks for also responding, these are some things in my vision for this feature to be implemented on each device:

- Status of `Connected' or `Disconnected`
- Button to `Start gnirehtet`
- Button to `Stop gnirehtet`
- Button to `View log` to monitor the connections

Global settings and local settings for each device:
- Checkbox of `auto-reconnect`
- Menu to select of which `network adapter` to reverse tether from
- Proxy setting to reverse tether from

If you have a flaky USB cable, then gnirehtet may disconnect intermittently, the auto-reconnect functionality will help to recover the connection.

The user may also have several network adapters, such as ethernet or wifi with each connected together to different networks. The option to select which adapter and proxy settings to use is another bonus.

**Comment by viarotel** [comment]
Hello there! I've carefully assessed your ideas and requirements, and I think they're really great. However, I currently don't want to invest too much time in this particular feature. Nevertheless, I've made some simple optimizations to it just now. You can give it a try. If you genuinely need this feature, please consider forking the project and contributing some code. I would greatly appreciate it. Thank you once again for your support.
