### ISSUE TITLE
运行一段时间后提示"操作失败"

### ISSUE THREAD

**Issue by tangzeyu7** [viarotel-org/escrcpy#92]
![image](https://github.com/viarotel-org/escrcpy/assets/20296836/d2f64403-4d57-4496-a7cc-37d8fd0830e8)

**Comment by viarotel** [comment]
这个一般是配置之间冲突引起的，请尝试重置配置，或者打开 Debug 提供一下运行日志给我

**Comment by viarotel** [comment]
我指的是所有配置 不仅仅是这个依赖配置

**Comment by tangzeyu7** [comment]
打开调试模式后,就不再出现这个问题了,关闭调试模式时,哪怕使用的默认配置,也会出现这个问题.

**Comment by viarotel** [comment]
@tangzeyu7 仅从你的描述和截图我无法推断出问题，请尝试打开开发者工具 为我提供更多信息
