### ISSUE TITLE
调整窗口大小后很模糊，分辨率已调整为1920

### ISSUE THREAD

**Issue by ooil929** [viarotel-org/escrcpy#94]
如下图，不管分辨率调整到多大，调整窗口大小后都非常模糊。
![image](https://github.com/viarotel-org/escrcpy/assets/39184577/3397c9e8-e26a-4544-af07-843773a7f09c)

**Comment by viarotel** [comment]
默认分辨率也模糊？ 我觉得这个调整之后模糊可能跟你显示器有关系 escrcpy 基于 scrcpy 原生控制窗口如果确实认为是BUG 请向 scrcpy 提 issue
