### ISSUE TITLE
电源键关闭屏幕和指纹、密码解锁屏幕都会出现操作失败，导致窗口崩溃。

### ISSUE THREAD

**Issue by yl9345** [viarotel-org/escrcpy#97]
遇到和Qtscrcpy一样的问题，能wifi正常镜像，但电源键关闭屏幕或自动息屏和指纹、密码解锁屏幕都会出现操作失败，导致窗口崩溃（Command failed with code 2）。
之前用还好好的，不清楚是手机设置哪里变了，还是电脑。
手机android 9，刚改过原生电池优化设置，也试着改回来，没效果。
电脑前几天刚下载搞机工具箱和QtAdb连过手机，用过之后就出现这种情况。
adb.exe的版本不一样？手机电脑重启也没用，搞不清楚。
正常运行到崩溃，日志就多了条：
[error] scrcpyProcess.stderr.data: WARN: Device disconnected

**Comment by viarotel** [comment]
你可以尝试自定义adb版本看看能否解决这个问题，遗憾的是我没有类似机型，所以我无法复现这个问题并帮到你

**Comment by yl9345** [comment]
谢谢回复，我觉得应该不是机型或安卓版本问题，毕竟这个手机Qtscrcpy我都用了一两年了都没问题，而且下了escrcpy出现的问题和Qtscrcpy一模一样，倒是像手机里的某个活动被限制了？只在息屏和解锁才出错，不知道abd镜像用到了手机内的哪个进程？
